"use client"
import { useEffect, useState } from "react"
import { BadgeDollarSign, CheckCircle2, CircleX, Inbox, Percent, ReceiptText } from "lucide-react"
import { supabase } from "@/lib/supabase"
import { EmptyState, MetricCard, money, QuotePage } from "./quoting-ui"
type QuoteRow = { id: string; customer_company: string | null; origin_city: string; origin_state: string; destination_city: string; destination_state: string; status: string; calculated_quote: number | null; calculated_rpm: number | null; created_at: string }
export function AutomatedFreightQuoting() {
  const [rows, setRows] = useState<QuoteRow[]>([]); const [loading, setLoading] = useState(true)
  useEffect(() => { void (async () => { const { data } = await supabase.from("gbgs_quote_requests").select("id,customer_company,origin_city,origin_state,destination_city,destination_state,status,calculated_quote,calculated_rpm,created_at").order("created_at", { ascending: false }).limit(100); setRows((data ?? []) as QuoteRow[]); setLoading(false) })() }, [])
  const today = new Date().toISOString().slice(0, 10), quoted = rows.filter((r) => r.status === "Quoted"), decided = rows.filter((r) => ["Accepted", "Rejected"].includes(r.status)), accepted = rows.filter((r) => r.status === "Accepted"), rpmRows = rows.filter((r) => r.calculated_rpm != null), total = rows.filter((r) => r.status !== "Declined").reduce((sum, r) => sum + Number(r.calculated_quote ?? 0), 0)
  return <QuotePage title="Quote Dashboard" description="Monitor incoming requests, opening rates, decisions, and quoted revenue."><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><MetricCard icon={Inbox} label="New Quote Requests" value={String(rows.filter((r) => r.status === "New").length)} sub="Awaiting pricing" /><MetricCard icon={CheckCircle2} label="Quoted Today" value={String(quoted.filter((r) => r.created_at.startsWith(today)).length)} sub="Opening quotes prepared" /><MetricCard icon={CircleX} label="Declined Today" value={String(rows.filter((r) => r.status === "Declined" && r.created_at.startsWith(today)).length)} sub="Hard-rule declines" /><MetricCard icon={Percent} label="Average Opening RPM" value={rpmRows.length ? `$${(rpmRows.reduce((s, r) => s + Number(r.calculated_rpm), 0) / rpmRows.length).toFixed(2)}` : "$0.00"} sub="Across calculated requests" /><MetricCard icon={BadgeDollarSign} label="Quote Acceptance Rate" value={decided.length ? `${Math.round(accepted.length / decided.length * 100)}%` : "0%"} sub="Accepted vs. decided" /><MetricCard icon={ReceiptText} label="Total Quoted Revenue" value={money(total)} sub="Calculated non-declined quotes" /></section><section className="rounded-2xl bg-card p-5 shadow-[0_20px_60px_-30px_rgba(8,28,53,0.22)]"><h2 className="text-lg font-bold text-[#081C35]">Recent Quote Requests</h2><div className="mt-4 overflow-x-auto">{loading ? <p className="text-sm text-muted-foreground">Loading quote requests...</p> : rows.length === 0 ? <EmptyState message="No quote requests yet. Use Quote Requests to calculate and save the first manual quote." /> : <table className="w-full min-w-[760px] text-left text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th className="pb-3">Customer</th><th>Lane</th><th>Status</th><th>Quote</th><th>RPM</th></tr></thead><tbody>{rows.slice(0, 8).map((r) => <tr key={r.id} className="border-t border-border"><td className="py-3 font-semibold text-[#081C35]">{r.customer_company || "Unassigned"}</td><td>{r.origin_city}, {r.origin_state} → {r.destination_city}, {r.destination_state}</td><td>{r.status}</td><td>{r.calculated_quote == null ? "—" : money(r.calculated_quote)}</td><td>{r.calculated_rpm == null ? "—" : `$${Number(r.calculated_rpm).toFixed(2)}`}</td></tr>)}</tbody></table>}</div></section></QuotePage>
}
