"use client"
import { useEffect, useState } from "react"
import { Save } from "lucide-react"
import { supabase } from "@/lib/supabase"
import { fieldClass, QuotePage } from "./quoting-ui"
type DistanceRule = { id: string; min_miles: number; max_miles: number | null; opening_rpm: number | null; minimum_charge: number | null; active: boolean }
type EquipmentRule = { id: string; equipment_type: string; active: boolean }
export function PricingRules() {
  const [distance, setDistance] = useState<DistanceRule[]>([]), [equipment, setEquipment] = useState<EquipmentRule[]>([]), [message, setMessage] = useState("")
  useEffect(() => { void (async () => { const [d, e] = await Promise.all([supabase.from("gbgs_quote_distance_rules").select("*").order("sort_order"), supabase.from("gbgs_quote_equipment_rules").select("*").order("equipment_type")]); setDistance((d.data ?? []) as DistanceRule[]); setEquipment((e.data ?? []) as EquipmentRule[]) })() }, [])
  async function save() { setMessage(""); const updates = [...distance.map((r) => supabase.from("gbgs_quote_distance_rules").update({ min_miles: r.min_miles, max_miles: r.max_miles, opening_rpm: r.opening_rpm, minimum_charge: r.minimum_charge, active: r.active }).eq("id", r.id)), ...equipment.map((r) => supabase.from("gbgs_quote_equipment_rules").update({ equipment_type: r.equipment_type, active: r.active }).eq("id", r.id))]; const results = await Promise.all(updates); setMessage(results.find((r) => r.error)?.error?.message ?? "Pricing rules saved.") }
  return <QuotePage title="Pricing Rules" description="Edit the database-driven distance bands and approved equipment used by the server pricing engine." action={<button onClick={save} className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#C9A227] px-4 text-sm font-bold text-[#081C35]"><Save className="h-4 w-4" />Save Rules</button>}>{message && <div className="rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm font-semibold text-green-700">{message}</div>}<section className="rounded-2xl bg-card p-5"><h2 className="text-lg font-bold text-[#081C35]">Distance Opening Rates</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="text-xs uppercase text-muted-foreground"><tr><th>Minimum Miles</th><th>Maximum Miles</th><th>Opening RPM</th><th>Minimum Charge</th><th>Active</th></tr></thead><tbody>{distance.map((r, index) => <tr key={r.id} className="border-t border-border"><td className="py-3 pr-3"><input type="number" value={r.min_miles} onChange={(e) => setDistance((rows) => rows.map((x, i) => i === index ? { ...x, min_miles: Number(e.target.value) } : x))} className={fieldClass} /></td><td className="pr-3"><input type="number" value={r.max_miles ?? ""} placeholder="No maximum" onChange={(e) => setDistance((rows) => rows.map((x, i) => i === index ? { ...x, max_miles: e.target.value ? Number(e.target.value) : null } : x))} className={fieldClass} /></td><td className="pr-3"><input type="number" step=".05" value={r.opening_rpm ?? ""} onChange={(e) => setDistance((rows) => rows.map((x, i) => i === index ? { ...x, opening_rpm: e.target.value ? Number(e.target.value) : null } : x))} className={fieldClass} /></td><td className="pr-3"><input type="number" value={r.minimum_charge ?? ""} onChange={(e) => setDistance((rows) => rows.map((x, i) => i === index ? { ...x, minimum_charge: e.target.value ? Number(e.target.value) : null } : x))} className={fieldClass} /></td><td><input type="checkbox" checked={r.active} onChange={(e) => setDistance((rows) => rows.map((x, i) => i === index ? { ...x, active: e.target.checked } : x))} /></td></tr>)}</tbody></table></div></section><section className="rounded-2xl bg-card p-5"><h2 className="text-lg font-bold text-[#081C35]">Approved Equipment</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{equipment.map((r, index) => <label key={r.id} className="flex items-center gap-3 rounded-xl border border-border p-3"><input type="checkbox" checked={r.active} onChange={(e) => setEquipment((rows) => rows.map((x, i) => i === index ? { ...x, active: e.target.checked } : x))} /><input value={r.equipment_type} onChange={(e) => setEquipment((rows) => rows.map((x, i) => i === index ? { ...x, equipment_type: e.target.value } : x))} className={fieldClass} /></label>)}</div></section></QuotePage>
}
