"use client"
import { useEffect, useState } from "react"
import { Mail, Save } from "lucide-react"
import { supabase } from "@/lib/supabase"
import type { QuoteSettings as SettingsType } from "@/lib/freight-quoting/types"
import { fieldClass, QuotePage } from "./quoting-ui"
type Row = SettingsType & { id: string }
export function QuoteSettings() {
  const [row, setRow] = useState<Row | null>(null), [message, setMessage] = useState("")
  useEffect(() => { void (async () => { const { data } = await supabase.from("gbgs_quote_settings").select("*").single(); setRow(data as Row | null) })() }, [])
  async function save() { if (!row) return; const { error } = await supabase.from("gbgs_quote_settings").update({ short_haul_max_miles: row.short_haul_max_miles, short_haul_minimum: row.short_haul_minimum, max_weight_lbs: row.max_weight_lbs, additional_stop_charge: row.additional_stop_charge, target_rpm: row.target_rpm, hard_floor_rpm: row.hard_floor_rpm, round_quote_to: row.round_quote_to, auto_quote_enabled: row.auto_quote_enabled, auto_decline_overweight: row.auto_decline_overweight, updated_at: new Date().toISOString() }).eq("id", row.id); setMessage(error?.message ?? "Settings saved.") }
  const numberField = (label: string, key: keyof SettingsType, step = "1") => row && <label className="grid gap-1.5 text-sm font-semibold text-[#081C35]">{label}<input type="number" step={step} value={String(row[key])} onChange={(e) => setRow({ ...row, [key]: Number(e.target.value) })} className={fieldClass} /></label>
  return <QuotePage title="Settings" description="Control company-specific quote limits, negotiation references, rounding, and automation readiness." action={<button onClick={save} disabled={!row} className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#C9A227] px-4 text-sm font-bold text-[#081C35] disabled:opacity-50"><Save className="h-4 w-4" />Save Settings</button>}>{message && <div className="rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm font-semibold text-green-700">{message}</div>}<section className="rounded-2xl bg-card p-5"><h2 className="text-lg font-bold text-[#081C35]">Quote Controls</h2>{row ? <div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{numberField("Maximum Weight (lbs)", "max_weight_lbs")}{numberField("Short Haul Maximum Miles", "short_haul_max_miles")}{numberField("Short Haul Minimum ($)", "short_haul_minimum", ".01")}{numberField("Additional Stop Charge ($)", "additional_stop_charge", ".01")}{numberField("Negotiation Target RPM", "target_rpm", ".01")}{numberField("Hard Floor RPM", "hard_floor_rpm", ".01")}{numberField("Quote Rounding Increment ($)", "round_quote_to", ".01")}<label className="flex items-center justify-between rounded-xl border border-border p-4 text-sm font-bold text-[#081C35]">Auto Quote <input type="checkbox" checked={row.auto_quote_enabled} onChange={(e) => setRow({ ...row, auto_quote_enabled: e.target.checked })} /></label><label className="flex items-center justify-between rounded-xl border border-border p-4 text-sm font-bold text-[#081C35]">Auto Decline Overweight <input type="checkbox" checked={row.auto_decline_overweight} onChange={(e) => setRow({ ...row, auto_decline_overweight: e.target.checked })} /></label></div> : <p className="mt-4 text-sm text-muted-foreground">Apply the quoting migration to create your settings record.</p>}</section><section className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-muted p-3"><Mail className="h-5 w-5 text-[#081C35]" /></div><div><h2 className="font-bold text-[#081C35]">Microsoft Shared Mailbox</h2><p className="text-sm font-bold text-red-600">NOT CONNECTED</p></div></div><button disabled className="mt-4 h-10 rounded-lg bg-muted px-4 text-sm font-bold text-muted-foreground opacity-60">Connect Microsoft Mailbox</button><p className="mt-2 text-xs text-muted-foreground">Mailbox connection and automatic sending are intentionally unavailable in V1.</p></section></QuotePage>
}
