"use client";

import { CheckCheck } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { NotificationItem, type NotificationData } from "@/components/miz-rita/notification-item";
import { supabase } from "@/lib/supabase";

const filters=["Orders","Kitchen","Deliveries","Inventory","Payments","Calendar","Unread","All"] as const;type Filter=typeof filters[number];const PAGE_SIZE=30;

export default function NotificationsPage(){
  const [items,setItems]=useState<NotificationData[]>([]);const [filter,setFilter]=useState<Filter>("All");const [businessId,setBusinessId]=useState("");const [loading,setLoading]=useState(true);const [loadingMore,setLoadingMore]=useState(false);const [hasMore,setHasMore]=useState(false);const [error,setError]=useState("");
  const loadPage=useCallback(async(reset:boolean)=>{reset?setLoading(true):setLoadingMore(true);setError("");let id=businessId;if(!id){const {data:business,error:businessError}=await supabase.from("gbgs_businesses").select("id").eq("slug","miz-ritas-kitchen").maybeSingle();if(businessError||!business){setError(businessError?.message??"Business not found.");setLoading(false);setLoadingMore(false);return;}id=business.id;setBusinessId(id);}const from=reset?0:items.length;const {data,error:notificationError}=await supabase.from("gbgs_notifications").select("id,category,title,message,severity,is_read,created_at,related_order:gbgs_orders!related_order_id(order_number,meal_count,delivery_method),related_customer:gbgs_customers!related_customer_id(first_name,last_name)").eq("business_id",id).order("created_at",{ascending:false}).range(from,from+PAGE_SIZE-1);if(notificationError){if(reset)setItems([]);setError(notificationError.message);}else{const rows=(data??[]) as unknown as NotificationData[];setItems((current)=>reset?rows:[...current,...rows.filter((row)=>!current.some((item)=>item.id===row.id))]);setHasMore(rows.length===PAGE_SIZE);}setLoading(false);setLoadingMore(false);},[businessId,items.length]);
  useEffect(()=>{void loadPage(true);},[]); // Initial page only; realtime handles subsequent inserts.
  useEffect(()=>{if(!businessId)return;const channel=supabase.channel(`notification-center-${businessId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"gbgs_notifications",filter:`business_id=eq.${businessId}`},()=>void loadPage(true)).subscribe();return()=>{void supabase.removeChannel(channel);};},[businessId,loadPage]);
  const visible=useMemo(()=>filter==="All"?items:filter==="Unread"?items.filter((item)=>!item.is_read):items.filter((item)=>item.category===filter),[filter,items]);const unread=items.filter((item)=>!item.is_read).length;
  const markRead=async(item:NotificationData)=>{if(item.is_read)return;setItems((current)=>current.map((entry)=>entry.id===item.id?{...entry,is_read:true}:entry));await supabase.from("gbgs_notifications").update({is_read:true}).eq("id",item.id).eq("business_id",businessId);};
  const markAllRead=async()=>{setItems((current)=>current.map((item)=>({...item,is_read:true})));await supabase.from("gbgs_notifications").update({is_read:true}).eq("business_id",businessId).eq("is_read",false);};
  return <main className="min-h-screen bg-slate-100 p-6 text-slate-900"><section className="rounded-3xl bg-[#081c35] p-7 text-white shadow-xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-[#d6a817]">Miz Rita HQ</p><h1 className="mt-2 text-3xl font-bold">Notification Center</h1><p className="mt-2 text-slate-300">Operational alerts from every part of the kitchen.</p></div><button disabled={!unread} onClick={()=>void markAllRead()} className="flex items-center gap-2 rounded-xl border border-white/20 px-4 py-3 font-bold disabled:opacity-40"><CheckCheck className="h-5 w-5" />Mark All Read</button></div></section>
  <div className="mt-6 flex flex-wrap gap-2">{filters.map((item)=><button key={item} onClick={()=>setFilter(item)} className={`rounded-xl px-4 py-2 text-sm font-bold ${filter===item?"bg-blue-600 text-white":"border border-slate-200 bg-white text-slate-700"}`}>{item}</button>)}</div>{error&&<p className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</p>}
  <section className="mt-5 overflow-hidden rounded-2xl bg-white shadow-sm"><div className="flex items-center justify-between border-b px-5 py-4"><h2 className="font-bold">{filter} Notifications</h2><span className="rounded-full bg-blue-50 px-3 py-1 text-sm font-bold text-blue-700">{unread} unread loaded</span></div>{loading?<p className="p-8 text-center text-slate-400">Loading notifications...</p>:visible.map((item)=><button key={item.id} onClick={()=>void markRead(item)} className="block w-full border-b px-5 py-4 text-left transition hover:bg-slate-50"><NotificationItem item={item} /></button>)}{!loading&&!visible.length&&<p className="p-10 text-center text-slate-400">No notifications yet.</p>}{hasMore&&<div className="p-4 text-center"><button disabled={loadingMore} onClick={()=>void loadPage(false)} className="rounded-xl border border-slate-200 px-5 py-2.5 text-sm font-bold text-blue-700 disabled:opacity-50">{loadingMore?"Loading...":"Load More"}</button></div>}</section></main>;
}
