"use client";

import { Save } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Settings={id:string;customer_emails:boolean;customer_sms:boolean;driver_notifications:boolean;kitchen_notifications:boolean;internal_notifications:boolean;future_push_notifications:boolean};
type Template={id:string;workflow_event:string;communication_type:string;audience:string;subject:string;message:string;is_enabled:boolean};
const switches:[keyof Omit<Settings,"id">,string][]=[["customer_emails","Customer Emails"],["customer_sms","Customer SMS"],["driver_notifications","Driver Notifications"],["kitchen_notifications","Kitchen Notifications"],["internal_notifications","Internal Notifications"],["future_push_notifications","Future Push Notifications"]];

export default function CommunicationSettingsPage(){
  const [businessId,setBusinessId]=useState("");const [settings,setSettings]=useState<Settings|null>(null);const [templates,setTemplates]=useState<Template[]>([]);const [saving,setSaving]=useState("");const [message,setMessage]=useState("");
  const load=useCallback(async()=>{const {data:business}=await supabase.from("gbgs_businesses").select("id").eq("slug","miz-ritas-kitchen").maybeSingle();if(!business)return;setBusinessId(business.id);const [settingResult,templateResult]=await Promise.all([supabase.from("gbgs_communication_settings").select("*").eq("business_id",business.id).single(),supabase.from("gbgs_communication_templates").select("id,workflow_event,communication_type,audience,subject,message,is_enabled").eq("business_id",business.id).order("workflow_event")]);if(settingResult.data)setSettings(settingResult.data as Settings);setTemplates((templateResult.data??[]) as Template[]);},[]);
  useEffect(()=>{void load();},[load]);
  const toggle=async(key:keyof Omit<Settings,"id">)=>{if(!settings)return;const value=!settings[key];setSettings({...settings,[key]:value});const {error}=await supabase.from("gbgs_communication_settings").update({[key]:value,updated_at:new Date().toISOString()}).eq("id",settings.id);setMessage(error?error.message:"Communication preference saved.");};
  const saveTemplate=async(template:Template)=>{setSaving(template.id);const {error}=await supabase.from("gbgs_communication_templates").update({subject:template.subject,message:template.message,is_enabled:template.is_enabled,updated_at:new Date().toISOString()}).eq("id",template.id).eq("business_id",businessId);setMessage(error?error.message:"Template saved.");setSaving("");};
  return <main className="min-h-screen bg-slate-100 p-6 text-slate-900"><section className="rounded-3xl bg-[#081c35] p-7 text-white shadow-xl"><p className="text-xs font-bold uppercase tracking-[.25em] text-[#d6a817]">Communication Center</p><h1 className="mt-2 text-3xl font-bold">Communication Settings</h1><p className="mt-2 text-slate-300">Control which communications enter the internal queue. No messages are sent externally.</p></section>{message&&<p className="mt-5 rounded-xl border border-blue-200 bg-blue-50 p-4 text-blue-800">{message}</p>}
  <section className="mt-6 rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-[#081c35]">Channels</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{switches.map(([key,label])=><button key={key} disabled={!settings} onClick={()=>void toggle(key)} className="flex items-center justify-between rounded-2xl border p-4 text-left"><span className="font-bold">{label}</span><span className={`relative h-7 w-12 rounded-full transition ${settings?.[key]?"bg-blue-600":"bg-slate-300"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${settings?.[key]?"left-6":"left-1"}`} /></span></button>)}</div></section>
  <section className="mt-6 rounded-3xl bg-white p-6 shadow-sm"><div><h2 className="text-xl font-bold text-[#081c35]">Message Templates</h2><p className="mt-1 text-sm text-slate-500">Available variables: {"{{customer_name}}, {{order_number}}, {{meal_count}}, {{pickup_time}}, {{delivery_time}}, {{driver_name}}, {{tracking_link}}, {{business_name}}, {{business_phone}}, {{business_email}}"}</p></div><div className="mt-5 space-y-4">{templates.map((template)=><article key={template.id} className="rounded-2xl border border-slate-200 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">{template.workflow_event}</p><p className="text-xs text-slate-500">{template.audience} · {template.communication_type}</p></div><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={template.is_enabled} onChange={(event)=>setTemplates((current)=>current.map((item)=>item.id===template.id?{...item,is_enabled:event.target.checked}:item))} />Enabled</label></div><label className="mt-4 block"><span className="mb-1 block text-sm font-bold">Subject</span><input value={template.subject} onChange={(event)=>setTemplates((current)=>current.map((item)=>item.id===template.id?{...item,subject:event.target.value}:item))} className="w-full rounded-xl border p-3" /></label><label className="mt-3 block"><span className="mb-1 block text-sm font-bold">Message</span><textarea rows={4} value={template.message} onChange={(event)=>setTemplates((current)=>current.map((item)=>item.id===template.id?{...item,message:event.target.value}:item))} className="w-full rounded-xl border p-3" /></label><button disabled={saving===template.id} onClick={()=>void saveTemplate(template)} className="mt-4 flex items-center gap-2 rounded-xl bg-[#081c35] px-4 py-2.5 font-bold text-white disabled:opacity-50"><Save className="h-4 w-4" />{saving===template.id?"Saving...":"Save Template"}</button></article>)}{!templates.length&&<p className="text-sm text-slate-400">No communication templates found.</p>}</div></section></main>;
}
