"use client"

import Link from "next/link"
import { useMemo, useState } from "react"
import { Activity, AlertTriangle, ArrowRight, CalendarDays, CheckCircle2, Church, Clock3, Flag, Heart, Pencil, Plus, Save, Sparkles, Trash2, UserRound, WalletCards, X } from "lucide-react"
import { Checkbox } from "@/components/ui/checkbox"
import { calculateAllocation, dailyMotivation, formatHours, formatTime, LIFE_AREAS, LIFE_AREA_STYLES, lifeAreaFor, unpackLifeNotes, type LifeArea, type LifeCalendarEvent, type TimeBlockForm } from "@/lib/life-hq"
import { useLifeHqToday } from "@/components/life-hq/use-life-hq-today"

export function LifeHqToday() {
  const data = useLifeHqToday()
  const [editor, setEditor] = useState<{ id?: string; form: TimeBlockForm } | null>(null)
  const allocation = useMemo(() => calculateAllocation(data.events), [data.events])
  const eventsFor = (area: LifeArea) => data.events.filter((event) => lifeAreaFor(event) === area)
  const dateLabel = new Date(`${data.todayKey}T12:00:00`).toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" })

  async function submitBlock() { if (!editor) return; const error = await data.saveTimeBlock(editor.form, editor.id); if (!error) setEditor(null); else data.setMessage(error) }

  return <div className="min-h-screen bg-[#F1F4F8] text-[#081C35]">
    <header className="border-b border-slate-200 bg-white px-4 py-5 sm:px-6"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.24em] text-[#C9A227]">Life HQ · Daily Personal Command Center</p><h1 className="text-3xl font-black">TODAY</h1><p className="mt-1 text-sm text-slate-500">Run the day. Protect what matters. Execute what matters.</p></div><div className="rounded-xl bg-slate-100 px-4 py-3 text-right"><p className="text-xs font-bold uppercase text-slate-500">Today</p><p className="font-bold">{dateLabel}</p></div></div></header>

    <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6">
      {data.message ? <div className="rounded-xl border border-[#C9A227]/30 bg-[#C9A227]/10 px-4 py-3 text-sm font-semibold">{data.message}</div> : null}

      <section className="rounded-3xl bg-[#081C35] p-6 text-white shadow-xl"><div className="flex items-center gap-2 text-[#C9A227]"><CheckCircle2 className="h-5 w-5" /><h2 className="text-xs font-black uppercase tracking-[.2em]">Today&apos;s Top 3</h2></div><p className="mt-2 text-sm text-white/60">Choose the three priorities that matter most today.</p><div className="mt-5 grid gap-3 lg:grid-cols-3">{data.today.top.map((item, index) => <div key={index} className="flex items-center gap-3 rounded-xl bg-white/10 p-3"><span className="text-sm font-black text-[#C9A227]">{index + 1}</span><Checkbox checked={data.today.topDone[index]} disabled={data.saving} onCheckedChange={(value) => void data.setTopCompleted(index, value === true)} /><input aria-label={`Priority ${index + 1}`} value={item} disabled={data.loading || data.saving} onChange={(event) => data.setToday((current) => { const top = [...current.top] as typeof current.top; top[index] = event.target.value; return { ...current, top } })} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); void data.saveTopPriority(index) } }} placeholder={`Add Priority ${index + 1}`} className={`min-w-0 flex-1 border-0 bg-transparent text-sm font-semibold outline-none placeholder:text-white/35 ${data.today.topDone[index] ? "text-white/45 line-through" : "text-white"}`} /><button type="button" onClick={() => void data.saveTopPriority(index)} disabled={data.loading || data.saving} aria-label={`Save Priority ${index + 1}`} className="rounded-lg p-1.5 text-[#C9A227] hover:bg-white/10 disabled:opacity-50"><Save className="h-4 w-4" /></button></div>)}</div></section>

      <section className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><CalendarDays className="text-[#C9A227]" /><h2 className="text-xl font-black">Today&apos;s Schedule</h2></div><p className="mt-1 text-sm text-slate-500">Every appointment, commitment, and intentional time block in chronological order</p></div><button onClick={() => setEditor({ form: { ...data.emptyTimeBlock } })} className="inline-flex items-center gap-2 rounded-xl bg-[#081C35] px-4 py-3 text-sm font-bold text-white"><Plus className="h-4 w-4" />Add Time Block</button></div><div className="mt-5 space-y-3">{data.loading ? <p className="text-slate-500">Loading today...</p> : data.events.length ? data.events.map((event) => <ScheduleRow key={event.id} event={event} onToggle={() => void data.toggleEvent(event)} onEdit={() => setEditor({ id: event.id, form: data.formForEvent(event) })} onDelete={() => void data.deleteEvent(event)} />) : <Empty text="No events or time blocks scheduled today." />}</div></section>

      <section><div className="mb-4"><h2 className="text-xl font-black">Today&apos;s Life Areas</h2><p className="mt-1 text-sm text-slate-500">What needs your attention across the important parts of your life today</p></div><div className="grid gap-5 lg:grid-cols-2 xl:grid-cols-3">
        <AreaCard title="Family" icon={Heart} href="/dashboard/life/family" hours={allocation.byArea.get("Family") ?? 0} warning="No intentional family time is scheduled."><EventList events={eventsFor("Family")} empty="No family commitments scheduled today." /></AreaCard>
        <AreaCard title="Fitness & Health" icon={Activity} href="/dashboard/life/health" hours={allocation.byArea.get("Fitness") ?? 0} warning="No fitness time is scheduled."><div className="grid grid-cols-3 gap-2"><ReadValue label="Workout" value={data.today.workout} /><ReadValue label="Weight" value={data.today.weight} /><ReadValue label="Protein" value={data.today.protein} /></div><EventList events={eventsFor("Fitness")} empty="No fitness block scheduled today." /></AreaCard>
        <AreaCard title="Faith" icon={Church} href="/dashboard/life/faith" hours={allocation.byArea.get("Faith") ?? 0} warning="No faith time is scheduled."><blockquote className="rounded-xl border-l-4 border-[#FBBF24] bg-blue-50 p-3 text-sm font-semibold italic">“{data.today.scripture}”<span className="mt-1 block text-xs not-italic text-[#9A6700]">{data.today.scriptureReference}</span></blockquote><div className="mt-3 grid gap-2 sm:grid-cols-3">{["Prayer", "Bible / Devotion", "Gratitude"].map((label, index) => <label key={label} className="flex items-center gap-2 text-xs font-bold"><Checkbox checked={data.today.faithDone[index]} disabled={data.saving} onCheckedChange={(value) => void data.setFaithCompleted(index, value === true)} />{label}</label>)}</div></AreaCard>
        <AreaCard title="Financial" icon={WalletCards} href="/dashboard/life/financial" hours={allocation.byArea.get("Financial") ?? 0}><EventList events={eventsFor("Financial")} empty="No financial items scheduled today." /></AreaCard>
        <AreaCard title="Personal" icon={UserRound} href="/dashboard/life" hours={allocation.byArea.get("Personal") ?? 0} warning="No personal or recovery time is scheduled."><EventList events={eventsFor("Personal")} empty="No personal commitments scheduled today." /></AreaCard>
        <AreaCard title="Personal Goals" icon={Flag} href="/dashboard/life/goals" hours={0}>{data.today.goalActions.length?<div><p className="mb-2 text-xs font-black text-slate-500">{data.today.goalActions.length} action{data.today.goalActions.length===1?"":"s"} today</p><div className="space-y-2">{[...data.today.goalActions].sort((a,b)=>({High:0,Medium:1,Low:2}[a.priority]-{High:0,Medium:1,Low:2}[b.priority])).slice(0,3).map(action=><label key={action.id} className="flex items-start gap-2 text-sm font-semibold"><Checkbox checked={action.status==="Completed"} disabled={data.saving} onCheckedChange={value=>void data.setGoalActionCompleted(action.id,value===true)}/><span className={action.status==="Completed"?"text-slate-400 line-through":""}>{action.action_title}</span></label>)}</div></div>:<p className="text-sm text-slate-500">No goal actions for today.</p>}</AreaCard>
      </div></section>

      <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-3xl bg-[#081C35] p-6 text-white shadow-sm"><div className="flex items-center gap-2 text-[#C9A227]"><Sparkles className="h-5 w-5" /><h2 className="text-xl font-black">Daily Motivation</h2></div><p className="mt-4 text-xl font-bold leading-relaxed">{dailyMotivation(data.todayKey)}</p></section><section className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex items-center gap-2"><Sparkles className="text-[#C9A227]" /><h2 className="text-xl font-black">Quick Capture</h2></div><textarea value={data.today.quickNote} onChange={(event) => data.setToday((current) => ({ ...current, quickNote: event.target.value }))} rows={3} placeholder="Capture something you don't want to forget..." className="mt-4 w-full resize-none rounded-2xl border border-slate-200 bg-slate-50 p-4 outline-none focus:border-[#C9A227]" /><div className="mt-3 flex justify-end"><button onClick={() => void data.saveQuickCapture()} disabled={data.saving} className="life-form-save inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-bold disabled:opacity-60"><Save className="h-4 w-4" />{data.saving ? "Saving..." : "Save Capture"}</button></div></section></div>

      <section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Today&apos;s Balance</h2><p className="mt-1 text-sm text-slate-500">A compact view of today&apos;s intentional time allocation</p><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4 xl:grid-cols-7"><AllocationStat label="Scheduled" value={allocation.total} /><AllocationStat label="Work / Business" value={allocation.work} />{(["Family", "Fitness", "Faith", "Financial", "Personal"] as LifeArea[]).map((area) => <AllocationStat key={area} label={area} value={allocation.byArea.get(area) ?? 0} />)}</div>{allocation.warnings.length ? <div className="mt-5 flex flex-wrap gap-2">{allocation.warnings.map((warning) => <span key={warning} className="inline-flex items-center gap-1 rounded-full bg-amber-50 px-3 py-2 text-xs font-bold text-amber-900"><AlertTriangle className="h-3.5 w-3.5" />{warning}</span>)}</div> : null}</section>
    </main>
    {editor ? <TimeBlockEditor editor={editor} saving={data.saving} onChange={(form) => setEditor((current) => current ? { ...current, form } : null)} onClose={() => setEditor(null)} onSave={() => void submitBlock()} /> : null}
  </div>
}

function ScheduleRow({ event, onToggle, onEdit, onDelete }: { event: LifeCalendarEvent; onToggle: () => void; onEdit: () => void; onDelete: () => void }) {
  const area = lifeAreaFor(event), notes = unpackLifeNotes(event.notes).notes, manageable = event.source === "Manual" || !event.source
  return <div className="flex items-start gap-3 rounded-2xl border border-slate-200 p-4"><Checkbox checked={event.completed} onCheckedChange={onToggle} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-black tabular-nums">{formatTime(event.start_time)}</span>{event.end_time ? <span className="text-sm text-slate-400">– {formatTime(event.end_time)}</span> : null}<span className={`rounded-full px-2 py-1 text-[11px] font-bold ${LIFE_AREA_STYLES[area]}`}>{area}</span></div><p className={`mt-2 font-bold ${event.completed ? "text-slate-400 line-through" : ""}`}>{event.title}</p>{notes ? <p className="mt-1 text-sm text-slate-500">{notes}</p> : null}</div><div className="flex items-center gap-1"><span className={`mr-1 hidden text-xs font-bold sm:inline ${event.completed ? "text-emerald-700" : "text-slate-400"}`}>{event.completed ? "Complete" : "Planned"}</span>{manageable ? <><button onClick={onEdit} aria-label={`Edit ${event.title}`} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><Pencil className="h-4 w-4" /></button><button onClick={onDelete} aria-label={`Delete ${event.title}`} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 className="h-4 w-4" /></button></> : null}</div></div>
}

function AreaCard({ title, icon: Icon, href, hours, warning, children }: { title: string; icon: typeof Heart; href: string; hours: number; warning?: string; children: React.ReactNode }) { return <section className="flex min-h-72 flex-col rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#081C35] text-[#C9A227]"><Icon className="h-4 w-4" /></span><h3 className="font-black">{title}</h3></div><span className={`rounded-full px-2 py-1 text-xs font-black ${hours ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}`}>{formatHours(hours)}</span></div><div className="mt-4 flex-1">{children}{!hours && warning ? <p className="mt-3 flex items-center gap-1 text-xs font-bold text-amber-800"><AlertTriangle className="h-3.5 w-3.5" />{warning}</p> : null}</div><Link href={href} className="mt-4 inline-flex items-center gap-1 text-sm font-black text-[#8A6C14]">Open {title} <ArrowRight className="h-4 w-4" /></Link></section> }
function EventList({ events, empty }: { events: LifeCalendarEvent[]; empty: string }) { return <div className="mt-3 space-y-2">{events.length ? events.map((event) => <div key={event.id} className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-black text-slate-500">{formatTime(event.start_time)}{event.end_time ? ` – ${formatTime(event.end_time)}` : ""}</p><p className={`mt-1 text-sm font-bold ${event.completed ? "text-slate-400 line-through" : ""}`}>{event.title}</p></div>) : <p className="text-sm text-slate-500">{empty}</p>}</div> }
function ReadValue({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-2"><span className="block text-[10px] font-black uppercase text-slate-500">{label}</span><p className="mt-1 truncate text-sm font-bold">{value || "—"}</p></div> }
function AllocationStat({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-1 text-xl font-black">{formatHours(value)}</p></div> }
function Empty({ text }: { text: string }) { return <div className="rounded-2xl bg-slate-50 p-8 text-center text-slate-500"><Clock3 className="mx-auto mb-3 h-8 w-8 text-[#C9A227]" />{text}</div> }

function TimeBlockEditor({ editor, saving, onChange, onClose, onSave }: { editor: { id?: string; form: TimeBlockForm }; saving: boolean; onChange: (form: TimeBlockForm) => void; onClose: () => void; onSave: () => void }) {
  const form = editor.form, field = <K extends keyof TimeBlockForm>(key: K, value: TimeBlockForm[K]) => onChange({ ...form, [key]: value })
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/60 p-4"><div className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#C9A227]">Life HQ Today</p><h2 className="text-2xl font-black">{editor.id ? "Edit Time Block" : "Add Time Block"}</h2></div><button onClick={onClose}><X /></button></div><div className="mt-5 grid gap-4"><Field label="Title"><input value={form.title} onChange={(event) => field("title", event.target.value)} className="life-input" /></Field><Field label="Planning Area"><select value={form.area} onChange={(event) => field("area", event.target.value as LifeArea)} className="life-input">{LIFE_AREAS.map((area) => <option key={area}>{area}</option>)}</select></Field><div className="grid grid-cols-2 gap-4"><Field label="Start"><input type="time" value={form.startTime} onChange={(event) => field("startTime", event.target.value)} className="life-input" /></Field><Field label="End"><input type="time" value={form.endTime} onChange={(event) => field("endTime", event.target.value)} className="life-input" /></Field></div><Field label="Notes"><textarea value={form.notes} onChange={(event) => field("notes", event.target.value)} rows={3} className="w-full rounded-xl border border-slate-200 p-3" /></Field></div><div className="mt-6 flex justify-end gap-3"><button onClick={onClose} className="life-form-cancel rounded-xl border px-4 py-3 font-bold">Cancel</button><button onClick={onSave} disabled={saving} className="life-form-save rounded-xl border px-4 py-3 font-bold disabled:opacity-60">{saving ? "Saving..." : editor.id ? "Save Changes" : "Add Block"}</button></div></div></div>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm font-bold">{label}<div className="mt-2 [&_.life-input]:h-11 [&_.life-input]:w-full [&_.life-input]:rounded-xl [&_.life-input]:border [&_.life-input]:border-slate-200 [&_.life-input]:px-3">{children}</div></label> }
