"use client"

import { useState } from "react"
import { AlertTriangle, CalendarDays, CheckCircle2, Clock3, Heart, Pencil, Plus, Trash2, X } from "lucide-react"
import { Checkbox } from "@/components/ui/checkbox"
import { formatHours, formatTime, unpackLifeNotes, type LifeCalendarEvent } from "@/lib/life-hq"
import { useFamilyCalendar, type FamilyCommitmentForm } from "@/components/life-hq/use-family-calendar"

const blankForm = (date: string): FamilyCommitmentForm => ({ title: "", date, startTime: "", endTime: "", notes: "" })

export function LifeHqFamily() {
  const data = useFamilyCalendar()
  const [editor, setEditor] = useState<{ id?: string; form: FamilyCommitmentForm; important?: boolean } | null>(null)
  const dateLabel = new Date(`${data.todayKey}T12:00:00`).toLocaleDateString("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" })
  async function submit() { if (!editor) return; const error = await data.saveCommitment(editor.form, editor.id); if (!error) setEditor(null); else data.setMessage(error) }

  return <div className="min-h-screen bg-[#F1F4F8] text-[#081C35]">
    <header className="border-b bg-white px-4 py-6 sm:px-6"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.24em] text-[#C9A227]">Life HQ</p><h1 className="text-3xl font-black">FAMILY</h1><p className="mt-1 text-sm text-slate-500">Protect the people who matter most.</p></div><div className="rounded-xl bg-slate-100 px-4 py-3 text-right"><p className="text-xs font-bold uppercase text-slate-500">Today</p><p className="font-bold">{dateLabel}</p></div></div></header>
    <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6">
      {data.message ? <p className="rounded-xl border border-[#C9A227]/30 bg-[#C9A227]/10 p-3 text-sm font-semibold">{data.message}</p> : null}
      <section className="rounded-3xl bg-[#081C35] p-6 text-white shadow-xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-[#C9A227]"><Heart /><h2 className="text-xl font-black text-white">Intentional Family Time</h2></div><p className="mt-2 text-sm text-white/60">Protect meaningful time before the week fills itself.</p></div><div className="grid grid-cols-2 gap-3"><TimeStat label="Today" value={data.todayHours} /><TimeStat label="This Week" value={data.weekHours} /></div></div><div className="mt-5 flex flex-wrap gap-2">{!data.todayHours ? <Warning text="No Family time is scheduled today." /> : null}{!data.weekHours ? <Warning text="No Family time is scheduled this week." /> : null}{data.todayHours && data.weekHours ? <span className="inline-flex items-center gap-1 rounded-full bg-emerald-500/20 px-3 py-2 text-xs font-bold text-emerald-200"><CheckCircle2 className="h-4 w-4" />Family time is protected.</span> : null}</div></section>

      <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
        <section className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">Today&apos;s Family Commitments</h2><p className="mt-1 text-sm text-slate-500">What your family needs from you today</p></div><button onClick={() => setEditor({ form: blankForm(data.todayKey) })} className="inline-flex items-center gap-2 rounded-xl bg-[#081C35] px-4 py-3 text-sm font-bold text-white"><Plus className="h-4 w-4" />Add Commitment</button></div><div className="mt-5 space-y-3">{data.loading ? <p className="text-slate-500">Loading family commitments...</p> : data.todayEvents.length ? data.todayEvents.map((event) => <FamilyRow key={event.id} event={event} today onToggle={() => void data.toggle(event)} onEdit={() => setEditor({ id: event.id, form: data.formFor(event) })} onDelete={() => void data.remove(event)} />) : <Empty text="No family commitments today." />}</div></section>
        <section className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Home & Family Responsibilities</h2><p className="mt-1 text-sm text-slate-500">Family items that need handling, even without a scheduled time</p><div className="mt-5 space-y-3">{data.responsibilities.length ? data.responsibilities.slice(0, 8).map((event) => <FamilyRow key={event.id} event={event} onToggle={() => void data.toggle(event)} onEdit={() => setEditor({ id: event.id, form: data.formFor(event) })} onDelete={() => void data.remove(event)} />) : <Empty text="No open family responsibilities." />}</div></section>
      </div>

      <section className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">Upcoming Family Commitments</h2><p className="mt-1 text-sm text-slate-500">The next 30 days of important family time and responsibilities</p></div><button onClick={() => setEditor({ form: blankForm(data.todayKey), important: true })} className="inline-flex items-center gap-2 rounded-xl border border-[#C9A227] px-4 py-3 text-sm font-bold text-[#081C35]"><CalendarDays className="h-4 w-4 text-[#C9A227]" />Add Important Date</button></div><div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.upcomingEvents.length ? data.upcomingEvents.map((event) => <FamilyRow key={event.id} event={event} onToggle={() => void data.toggle(event)} onEdit={() => setEditor({ id: event.id, form: data.formFor(event) })} onDelete={() => void data.remove(event)} />) : <Empty text="No upcoming family commitments in the next 30 days." />}</div></section>
    </main>
    {editor ? <FamilyEditor editor={editor} saving={data.saving} onChange={(form) => setEditor((current) => current ? { ...current, form } : null)} onClose={() => setEditor(null)} onSave={() => void submit()} /> : null}
  </div>
}

function FamilyRow({ event, today, onToggle, onEdit, onDelete }: { event: LifeCalendarEvent; today?: boolean; onToggle: () => void; onEdit: () => void; onDelete: () => void }) {
  const notes = unpackLifeNotes(event.notes).notes
  const manageable = event.source === "Manual" || !event.source
  return <article className="flex items-start gap-3 rounded-2xl border border-slate-200 p-4"><Checkbox checked={event.completed} onCheckedChange={onToggle} /><div className="min-w-0 flex-1"><p className="text-xs font-black uppercase text-[#9B7A17]">{today ? formatTime(event.start_time) : new Date(`${event.event_date}T12:00:00`).toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" })}{!today && event.start_time ? ` · ${formatTime(event.start_time)}` : ""}{event.end_time ? ` – ${formatTime(event.end_time)}` : ""}</p><p className={`mt-1 font-bold ${event.completed ? "text-slate-400 line-through" : ""}`}>{event.title}</p>{notes ? <p className="mt-1 text-sm text-slate-500">{notes}</p> : null}</div>{manageable ? <div className="flex"><button onClick={onEdit} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" aria-label={`Edit ${event.title}`}><Pencil className="h-4 w-4" /></button><button onClick={onDelete} className="rounded-lg p-2 text-red-600 hover:bg-red-50" aria-label={`Delete ${event.title}`}><Trash2 className="h-4 w-4" /></button></div> : null}</article>
}
function TimeStat({ label, value }: { label: string; value: number }) { return <div className="rounded-xl bg-white/10 px-5 py-3 text-center"><p className="text-xs font-bold uppercase text-white/50">{label}</p><p className="mt-1 text-2xl font-black text-[#C9A227]">{formatHours(value)}</p></div> }
function Warning({ text }: { text: string }) { return <span className="inline-flex items-center gap-1 rounded-full bg-amber-400/15 px-3 py-2 text-xs font-bold text-amber-200"><AlertTriangle className="h-4 w-4" />{text}</span> }
function Empty({ text }: { text: string }) { return <div className="rounded-2xl bg-slate-50 p-6 text-center text-sm text-slate-500"><Clock3 className="mx-auto mb-2 h-6 w-6 text-[#C9A227]" />{text}</div> }

function FamilyEditor({ editor, saving, onChange, onClose, onSave }: { editor: { id?: string; form: FamilyCommitmentForm; important?: boolean }; saving: boolean; onChange: (form: FamilyCommitmentForm) => void; onClose: () => void; onSave: () => void }) {
  const form = editor.form, field = <K extends keyof FamilyCommitmentForm>(key: K, value: FamilyCommitmentForm[K]) => onChange({ ...form, [key]: value })
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/60 p-4"><div className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#C9A227]">Family</p><h2 className="text-2xl font-black">{editor.id ? "Edit Family Commitment" : editor.important ? "Add Important Family Date" : "Add Family Commitment"}</h2></div><button onClick={onClose}><X /></button></div><div className="mt-5 grid gap-4"><Field label="Title"><input value={form.title} onChange={(event) => field("title", event.target.value)} className="family-input" placeholder={editor.important ? "Birthday, school event, appointment..." : "Family commitment"} /></Field><Field label="Date"><input type="date" value={form.date} onChange={(event) => field("date", event.target.value)} className="family-input" /></Field><div className="grid grid-cols-2 gap-4"><Field label="Start Time (optional)"><input type="time" value={form.startTime} onChange={(event) => field("startTime", event.target.value)} className="family-input" /></Field><Field label="End Time (optional)"><input type="time" value={form.endTime} onChange={(event) => field("endTime", event.target.value)} className="family-input" /></Field></div><Field label="Notes"><textarea value={form.notes} onChange={(event) => field("notes", event.target.value)} rows={3} className="w-full rounded-xl border border-slate-200 p-3" /></Field></div><div className="mt-6 flex justify-end gap-3"><button onClick={onClose} className="life-form-cancel rounded-xl border px-4 py-3 font-bold">Cancel</button><button onClick={onSave} disabled={saving} className="life-form-save rounded-xl border px-4 py-3 font-bold disabled:opacity-60">{saving ? "Saving..." : editor.id ? "Save Changes" : "Add to Family Calendar"}</button></div></div></div>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-sm font-bold">{label}<div className="mt-2 [&_.family-input]:h-11 [&_.family-input]:w-full [&_.family-input]:rounded-xl [&_.family-input]:border [&_.family-input]:border-slate-200 [&_.family-input]:px-3">{children}</div></label> }
