"use client"

import { useEffect, useMemo, useState } from "react"
import { ChevronLeft, ChevronRight, X } from "lucide-react"
import { supabase } from "@/lib/supabase"

const keyFor=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`

export function NutritionDateModal({open,value,onSelect,onClose}:{open:boolean;value:string;onSelect:(date:string)=>void;onClose:()=>void}){
  const selected=new Date(`${value}T12:00:00`)
  const[month,setMonth]=useState(()=>new Date(selected.getFullYear(),selected.getMonth(),1))
  const[nutritionStatuses,setNutritionStatuses]=useState<Map<string,"planned"|"completed">>(new Map()),[indicatorError,setIndicatorError]=useState("")
  useEffect(()=>{if(open)setMonth(new Date(selected.getFullYear(),selected.getMonth(),1))},[open,value])
  useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape")onClose()};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[open,onClose])
  useEffect(()=>{if(!open)return;let cancelled=false;void(async()=>{setIndicatorError("");const{data:userData,error:userError}=await supabase.auth.getUser();if(cancelled)return;if(userError||!userData.user){setNutritionStatuses(new Map());setIndicatorError(userError?.message??"Sign in required to load nutrition dates.");return}const start=keyFor(new Date(month.getFullYear(),month.getMonth(),1)),end=keyFor(new Date(month.getFullYear(),month.getMonth()+1,1)),dailyResult=await supabase.from("gbgs_life_daily_health").select("id,record_date,nutrition_completed").eq("user_id",userData.user.id).gte("record_date",start).lt("record_date",end);if(cancelled)return;if(dailyResult.error){setNutritionStatuses(new Map());setIndicatorError(dailyResult.error.message);return}const dailyRows=(dailyResult.data??[]) as{id:string;record_date:string;nutrition_completed:boolean}[],statuses=new Map<string,"planned"|"completed">(dailyRows.filter(row=>row.nutrition_completed).map(row=>[row.record_date,"completed"]));if(!dailyRows.length){setNutritionStatuses(statuses);return}const mealsResult=await supabase.from("gbgs_life_health_meals").select("daily_health_id,gbgs_life_health_food_items!inner(id)").eq("user_id",userData.user.id).in("daily_health_id",dailyRows.map(row=>row.id));if(cancelled)return;if(mealsResult.error){setNutritionStatuses(new Map());setIndicatorError(mealsResult.error.message);return}const datesById=new Map(dailyRows.map(row=>[row.id,row.record_date]));for(const meal of mealsResult.data??[]){const date=datesById.get(meal.daily_health_id);if(date&&!statuses.has(date))statuses.set(date,"planned")}setNutritionStatuses(statuses)})();return()=>{cancelled=true}},[open,month])
  const cells=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1),last=new Date(month.getFullYear(),month.getMonth()+1,0),result:(number|null)[]=Array(first.getDay()).fill(null);for(let day=1;day<=last.getDate();day++)result.push(day);while(result.length%7)result.push(null);return result},[month])
  if(!open)return null
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-[#071F3D]/60 p-4" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section role="dialog" aria-modal="true" aria-label="Select nutrition date" className="w-full max-w-lg overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex items-center justify-between bg-[#071F3D] px-5 py-3"><h2 className="text-sm font-black uppercase tracking-wide text-[#FBBF24]">Nutrition Log Calendar</h2><button onClick={onClose} className="icon-button text-white" aria-label="Close nutrition calendar"><X className="h-5 w-5"/></button></header><div className="p-4"><div className="mb-4 flex items-center justify-between"><button onClick={()=>setMonth(current=>new Date(current.getFullYear(),current.getMonth()-1,1))} className="quick-button" aria-label="Previous month"><ChevronLeft className="h-4 w-4"/></button><h3 className="text-lg font-black text-[#071F3D]">{month.toLocaleDateString("en-US",{month:"long",year:"numeric"})}</h3><button onClick={()=>setMonth(current=>new Date(current.getFullYear(),current.getMonth()+1,1))} className="quick-button" aria-label="Next month"><ChevronRight className="h-4 w-4"/></button></div>{indicatorError?<p className="mb-2 text-center text-[10px] font-bold text-red-600">{indicatorError}</p>:null}<div className="grid grid-cols-7 border-b text-center text-[10px] font-black text-slate-500">{["SUN","MON","TUE","WED","THU","FRI","SAT"].map(label=><div key={label} className="py-2">{label}</div>)}</div><div className="grid grid-cols-7">{cells.map((day,index)=>{if(!day)return <div key={`blank-${index}`} className="min-h-14 border-b border-r border-slate-100"/>;const date=keyFor(new Date(month.getFullYear(),month.getMonth(),day)),active=date===value,status=nutritionStatuses.get(date);return <button key={date} onClick={()=>{onSelect(date);onClose()}} className={`relative min-h-14 border-b border-r border-slate-100 text-xs font-bold hover:bg-blue-50 ${active?"bg-[#071F3D] text-[#FBBF24]":"text-[#071F3D]"}`}><span>{day}</span>{status?<span aria-label={status==="completed"?"Nutrition completed":"Nutrition planned"} className={`pointer-events-none absolute bottom-2 left-1/2 h-1.5 w-1.5 -translate-x-1/2 rounded-full ${status==="completed"?"bg-emerald-500":"bg-[#FBBF24]"}`}/>:null}</button>})}</div><div className="mt-3 flex items-center justify-center gap-5 text-[10px] font-bold text-slate-600"><span className="flex items-center gap-1.5"><i className="h-1.5 w-1.5 rounded-full bg-[#FBBF24]"/>Planned</span><span className="flex items-center gap-1.5"><i className="h-1.5 w-1.5 rounded-full bg-emerald-500"/>Completed</span></div><div className="mt-4 flex justify-end"><button onClick={onClose} className="cancel-button life-form-cancel">Close</button></div></div></section></div>
}
