"use client"

import { useCallback, useEffect, useState } from "react"
import { supabase } from "@/lib/supabase"
import { localDateKey, packLifeNotes } from "@/lib/life-hq"

export type WorkoutStatus = "Planned" | "Completed" | "Skipped"
export type DailyHealthRecord = { id:string; user_id:string; record_date:string; workout_name:string; workout_time:string|null; workout_status:WorkoutStatus; workout_notes:string; weight_lbs:number|null; protein_target_g:number|null; calorie_target:number|null; water_target_oz:number|null; calendar_event_id:string|null; nutrition_completed:boolean }
export type ExerciseSet = { id:string; exercise_id:string; set_number:number; reps:number; weight_used:number|null; weight_unit:string; notes:string; updated_at:string }
export type Exercise = { id:string; exercise_name:string; weight_used:number|null; weight_unit:string; notes:string; sort_order:number; group_id:string|null; group_position:number|null; sets:ExerciseSet[] }
export type ExerciseGroup = { id:string; user_id:string; daily_health_id:string; group_type:"Superset"|"Tri-set"|"Giant Set"|"Circuit"; group_name:string; sort_order:number; created_at:string; updated_at:string }
export type FoodItem = { id:string; meal_id:string; recipe_id?:string|null; custom_food_id?:string|null; food_name:string; serving_amount:number|null; serving_unit:string; grams_consumed:number|null; protein_g:number; carbohydrates_g:number; fat_g:number; calories:number; nutrition_source:string; external_food_id:string|null; source_food_name:string|null; protein_per_100g:number|null; carbohydrates_per_100g:number|null; fat_per_100g:number|null; calories_per_100g:number|null; manually_overridden:boolean; sort_order:number }
export type Meal = { id:string; daily_health_id:string; meal_label:string; meal_name:string; meal_time:string|null; sort_order:number; foods:FoodItem[] }
export type WaterEntry = { id:string; daily_health_id:string; amount_oz:number; consumed_at:string }
export type Supplement = { id:string; daily_health_id:string; supplement_name:string; amount:number|null; unit:string; taken:boolean; taken_at:string|null; sort_order:number }
export type NutritionTotals = { protein:number; carbs:number; fat:number; calories:number }
export type DailyHealthForm = { workoutName:string; workoutTime:string; workoutStatus:WorkoutStatus; workoutNotes:string; weightLbs:string; proteinTargetG:string; calorieTarget:string; waterTargetOz:string }
export type ExerciseSetForm = { reps:string; weight:string; unit:string; notes:string }
export type ExerciseForm = { name:string; sets:ExerciseSetForm[] }
export type MealForm = { label:string; name:string; time:string }
export type FoodForm = { name:string; servingAmount:string; servingUnit:string; grams:string; protein:string; carbs:string; fat:string; calories:string; nutritionSource:string; externalFoodId:string; sourceFoodName:string; proteinPer100g:string; carbsPer100g:string; fatPer100g:string; caloriesPer100g:string; manuallyOverridden:boolean }
export type FoodItemAppend = { recipe_id?:string|null; custom_food_id?:string|null; food_name:string; serving_amount:number|null; serving_unit:string; grams_consumed:number|null; protein_g:number; carbohydrates_g:number; fat_g:number; calories:number; nutrition_source:string; external_food_id:string|null; source_food_name:string|null; protein_per_100g:number|null; carbohydrates_per_100g:number|null; fat_per_100g:number|null; calories_per_100g:number|null; manually_overridden:boolean }
export type WaterForm = { amount:string; time:string }
export type SupplementForm = { name:string; amount:string; unit:string; taken:boolean; time:string }
export type DaySummary = { date:string; record:DailyHealthRecord|null; nutrition:NutritionTotals; water:number; supplementsTaken:number; supplementsTotal:number; workoutPct:number|null; nutritionPct:number|null; waterPct:number|null; supplementsPct:number|null }

const EMPTY_FORM:DailyHealthForm={workoutName:"",workoutTime:"",workoutStatus:"Planned",workoutNotes:"",weightLbs:"",proteinTargetG:"",calorieTarget:"",waterTargetOz:""}
const num=(value:string)=>value.trim()===""?null:Number(value)
const textNum=(value:number|null)=>value===null?"":String(value)
const timeNow=()=>{const date=new Date();return `${String(date.getHours()).padStart(2,"0")}:${String(date.getMinutes()).padStart(2,"0")}`}
const dateShift=(key:string,days:number)=>{const date=new Date(`${key}T12:00:00`);date.setDate(date.getDate()+days);return localDateKey(date)}
const weekBounds=(key:string)=>{const date=new Date(`${key}T12:00:00`);const mondayOffset=(date.getDay()+6)%7;return {start:dateShift(key,-mondayOffset),end:dateShift(key,6-mondayOffset)}}
const formFor=(record:DailyHealthRecord|null):DailyHealthForm=>record?{workoutName:record.workout_name,workoutTime:record.workout_time?.slice(0,5)??"",workoutStatus:record.workout_status,workoutNotes:record.workout_notes,weightLbs:textNum(record.weight_lbs),proteinTargetG:textNum(record.protein_target_g),calorieTarget:textNum(record.calorie_target),waterTargetOz:textNum(record.water_target_oz)}:{...EMPTY_FORM}
const totalsFor=(foods:FoodItem[]):NutritionTotals=>foods.reduce((sum,item)=>({protein:sum.protein+Number(item.protein_g),carbs:sum.carbs+Number(item.carbohydrates_g),fat:sum.fat+Number(item.fat_g),calories:sum.calories+Number(item.calories)}),{protein:0,carbs:0,fat:0,calories:0})
const capped=(current:number,target:number|null)=>target&&target>0?Math.min(100,current/target*100):null
const nutritionScore=(totals:NutritionTotals,record:DailyHealthRecord|null)=>{if(!record)return null;const protein=capped(totals.protein,record.protein_target_g),calories=record.calorie_target&&record.calorie_target>0?(totals.calories===0?0:Math.min(totals.calories/record.calorie_target,record.calorie_target/totals.calories)*100):null;const scores=[protein,calories].filter((v):v is number=>v!==null);return scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:null}

export function useLifeHqHealth(){
  const todayKey=localDateKey()
  const [selectedDate,setSelectedDate]=useState(todayKey)
  const nutritionDate=selectedDate,setNutritionDate=setSelectedDate
  const [record,setRecord]=useState<DailyHealthRecord|null>(null)
  const [nutritionRecord,setNutritionRecord]=useState<DailyHealthRecord|null>(null)
  const [form,setForm]=useState<DailyHealthForm>({...EMPTY_FORM})
  const [exercises,setExercises]=useState<Exercise[]>([])
  const [exerciseGroups,setExerciseGroups]=useState<ExerciseGroup[]>([])
  const [meals,setMeals]=useState<Meal[]>([])
  const [waterEntries,setWaterEntries]=useState<WaterEntry[]>([])
  const [supplements,setSupplements]=useState<Supplement[]>([])
  const [recentFoods,setRecentFoods]=useState<FoodItem[]>([])
  const [week,setWeek]=useState<DaySummary[]>([])
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("")

  const load=useCallback(async()=>{
    setLoading(true);setMessage("")
    const {data:userData,error:userError}=await supabase.auth.getUser()
    if(userError||!userData.user){setMessage(userError?.message??"Sign in required.");setLoading(false);return}
    const bounds=weekBounds(selectedDate)
    const [dailyResult,nutritionDailyResult,recentResult]=await Promise.all([
      supabase.from("gbgs_life_daily_health").select("*").eq("user_id",userData.user.id).gte("record_date",bounds.start).lte("record_date",bounds.end).order("record_date"),
      supabase.from("gbgs_life_daily_health").select("*").eq("user_id",userData.user.id).eq("record_date",nutritionDate).maybeSingle(),
      supabase.from("gbgs_life_health_food_items").select("*").eq("user_id",userData.user.id).order("created_at",{ascending:false}).limit(50),
    ])
    const {data:dailyData,error:dailyError}=dailyResult
    if(dailyError){setMessage(dailyError.message);setLoading(false);return}
    if(nutritionDailyResult.error){setMessage(nutritionDailyResult.error.message);setLoading(false);return}
    const daily=(dailyData??[]) as DailyHealthRecord[],nutritionSelected=(nutritionDailyResult.data as DailyHealthRecord|null)??null
    if(nutritionSelected&&!daily.some(item=>item.id===nutritionSelected.id))daily.push(nutritionSelected)
    const ids=daily.map(item=>item.id),selected=daily.find(item=>item.record_date===selectedDate)??null
    if(recentResult.error){setMessage(recentResult.error.message);setLoading(false);return}
    const recentSeen=new Set<string>();setRecentFoods(((recentResult.data??[]) as FoodItem[]).filter(item=>{const key=item.external_food_id?`${item.nutrition_source}:${item.external_food_id}`:item.food_name.trim().toLowerCase();if(recentSeen.has(key))return false;recentSeen.add(key);return true}).slice(0,8))
    let exerciseRows:any[]=[],groupRows:any[]=[],setRows:any[]=[],mealRows:any[]=[],foodRows:any[]=[],waterRows:any[]=[],supplementRows:any[]=[]
    if(ids.length){
      const [exerciseResult,groupResult,mealResult,waterResult,supplementResult]=await Promise.all([
        supabase.from("gbgs_life_health_exercises").select("*").in("daily_health_id",ids).order("sort_order"),
        supabase.from("gbgs_life_health_exercise_groups").select("*").in("daily_health_id",ids).order("sort_order"),
        supabase.from("gbgs_life_health_meals").select("*").in("daily_health_id",ids).order("sort_order"),
        supabase.from("gbgs_life_health_water_entries").select("*").in("daily_health_id",ids).order("consumed_at"),
        supabase.from("gbgs_life_health_supplements").select("*").in("daily_health_id",ids).order("sort_order"),
      ])
      const firstError=exerciseResult.error??groupResult.error??mealResult.error??waterResult.error??supplementResult.error
      if(firstError){setMessage(firstError.message);setLoading(false);return}
      exerciseRows=exerciseResult.data??[];groupRows=groupResult.data??[];mealRows=mealResult.data??[];waterRows=waterResult.data??[];supplementRows=supplementResult.data??[]
      if(exerciseRows.length){const result=await supabase.from("gbgs_life_health_exercise_sets").select("*").in("exercise_id",exerciseRows.map(item=>item.id)).order("set_number");if(result.error){setMessage(result.error.message);setLoading(false);return}setRows=result.data??[]}
      if(mealRows.length){const result=await supabase.from("gbgs_life_health_food_items").select("*").in("meal_id",mealRows.map(item=>item.id)).order("sort_order");if(result.error){setMessage(result.error.message);setLoading(false);return}foodRows=result.data??[]}
    }
    const mealModels:Meal[]=mealRows.map(item=>({...item,foods:foodRows.filter(food=>food.meal_id===item.id)}))
    const summaries:string[]=[];for(let date=bounds.start;date<=bounds.end;date=dateShift(date,1))summaries.push(date)
    setWeek(summaries.map(date=>{const dayRecord=daily.find(item=>item.record_date===date)??null,dayIds=dayRecord?[dayRecord.id]:[],dayFoods=mealModels.filter(item=>dayIds.includes(item.daily_health_id)).flatMap(item=>item.foods),nutrition=totalsFor(dayFoods),dayWater=waterRows.filter(item=>dayIds.includes(item.daily_health_id)).reduce((sum,item)=>sum+Number(item.amount_oz),0),daySupplements=supplementRows.filter(item=>dayIds.includes(item.daily_health_id)),supplementPct=daySupplements.length?daySupplements.filter(item=>item.taken).length/daySupplements.length*100:null;return{date,record:dayRecord,nutrition,water:dayWater,supplementsTaken:daySupplements.filter(item=>item.taken).length,supplementsTotal:daySupplements.length,workoutPct:dayRecord?.workout_status==="Completed"?100:dayRecord?.workout_name?0:null,nutritionPct:nutritionScore(nutrition,dayRecord),waterPct:capped(dayWater,dayRecord?.water_target_oz??null),supplementsPct:supplementPct}}))
    setRecord(selected);setNutritionRecord(nutritionSelected);setForm(formFor(selected));setExerciseGroups(groupRows.filter(item=>item.daily_health_id===selected?.id));setExercises(exerciseRows.filter(item=>item.daily_health_id===selected?.id).map(item=>({...item,sets:setRows.filter(set=>set.exercise_id===item.id)})));setMeals(mealModels.filter(item=>item.daily_health_id===nutritionSelected?.id));setWaterEntries(waterRows.filter(item=>item.daily_health_id===selected?.id));setSupplements(supplementRows.filter(item=>item.daily_health_id===selected?.id));setLoading(false)
  },[selectedDate,nutritionDate])
  useEffect(()=>{void load()},[load])

  async function persistDaily(overrides:Partial<DailyHealthForm>={}){
    const effective={...form,...overrides},values=[effective.weightLbs,effective.proteinTargetG,effective.calorieTarget,effective.waterTargetOz];if(values.some(value=>value&&(!Number.isFinite(Number(value))||Number(value)<0))){setMessage("Targets and body weight must be numbers of zero or greater.");return null}
    const {data:userData}=await supabase.auth.getUser();if(!userData.user){setMessage("Sign in required.");return null}const now=new Date().toISOString()
    const {data,error}=await supabase.from("gbgs_life_daily_health").upsert({user_id:userData.user.id,record_date:selectedDate,workout_name:effective.workoutName.trim(),workout_time:effective.workoutTime||null,workout_status:effective.workoutStatus,workout_notes:effective.workoutNotes.trim(),weight_lbs:num(effective.weightLbs),protein_target_g:num(effective.proteinTargetG),calorie_target:num(effective.calorieTarget),water_target_oz:num(effective.waterTargetOz),updated_at:now},{onConflict:"user_id,record_date"}).select("*").single()
    if(error||!data){setMessage(error?.message??"Unable to save daily health.");return null}let saved=data as DailyHealthRecord
    const shouldSync=Boolean(saved.workout_name&&saved.workout_time)
    if(!shouldSync&&saved.calendar_event_id){const deleted=await supabase.from("gbgs_calendar_events").delete().eq("id",saved.calendar_event_id).eq("user_id",userData.user.id).eq("source","Life Health");if(deleted.error){setMessage(`Health saved, but calendar sync failed: ${deleted.error.message}`);return saved}const cleared=await supabase.from("gbgs_life_daily_health").update({calendar_event_id:null,updated_at:now}).eq("id",saved.id).eq("user_id",userData.user.id).select("*").single();if(cleared.data)saved=cleared.data as DailyHealthRecord}
    if(shouldSync){const calendarPayload={title:`Workout: ${saved.workout_name}`,event_date:selectedDate,start_time:saved.workout_time,end_time:null,category:"Health",notes:packLifeNotes(saved.workout_notes,"Fitness"),completed:saved.workout_status==="Completed",source:"Life Health",source_id:saved.id,updated_at:now};let calendarId=saved.calendar_event_id;if(!calendarId){const existing=await supabase.from("gbgs_calendar_events").select("id").eq("user_id",userData.user.id).eq("source","Life Health").eq("source_id",saved.id).maybeSingle();calendarId=existing.data?.id??null}const result=calendarId?await supabase.from("gbgs_calendar_events").update(calendarPayload).eq("id",calendarId).eq("user_id",userData.user.id).select("id").single():await supabase.from("gbgs_calendar_events").insert({...calendarPayload,user_id:userData.user.id}).select("id").single();if(result.error||!result.data){setMessage(`Health saved, but calendar sync failed: ${result.error?.message??"Unknown error"}`);return saved}if(saved.calendar_event_id!==result.data.id){const linked=await supabase.from("gbgs_life_daily_health").update({calendar_event_id:result.data.id,updated_at:now}).eq("id",saved.id).eq("user_id",userData.user.id).select("*").single();if(linked.data)saved=linked.data as DailyHealthRecord}}
    setRecord(saved);return saved
  }
  async function ensureDaily(){return record??await persistDaily()}
  async function ensureNutritionDaily(){if(nutritionRecord)return nutritionRecord;if(nutritionDate===selectedDate)return record??await persistDaily();const{data:userData}=await supabase.auth.getUser();if(!userData.user){setMessage("Sign in required.");return null}const result=await supabase.from("gbgs_life_daily_health").insert({user_id:userData.user.id,record_date:nutritionDate}).select("*").single();if(result.error||!result.data){setMessage(result.error?.message??"Unable to create nutrition date.");return null}setNutritionRecord(result.data as DailyHealthRecord);return result.data as DailyHealthRecord}
  async function finish(text:string){await load();setMessage(text);setSaving(false);return true}
  async function saveDaily(){setSaving(true);const saved=await persistDaily();if(!saved){setSaving(false);return false}return finish("Daily plan and targets saved.")}
  async function completeWorkout(){if(form.workoutStatus==="Completed")return true;setSaving(true);const saved=await persistDaily({workoutStatus:"Completed"});if(!saved){setSaving(false);return false}return finish("Workout completed.")}

  async function saveExercise(input:ExerciseForm){if(!input.name.trim()||!input.sets.length||input.sets.some(set=>!Number.isInteger(Number(set.reps))||Number(set.reps)<0||(set.weight!==""&&Number(set.weight)<0))){setMessage("Add an exercise name and valid reps and weight for every set.");return false}setSaving(true);const daily=await ensureDaily();const {data:userData}=await supabase.auth.getUser();if(!daily||!userData.user){setSaving(false);return false}const result=await supabase.from("gbgs_life_health_exercises").insert({user_id:userData.user.id,daily_health_id:daily.id,exercise_name:input.name.trim(),weight_used:null,weight_unit:"lbs",notes:"",sort_order:[...exercises.filter(item=>!item.group_id).map(item=>item.sort_order),...exerciseGroups.map(item=>item.sort_order)].reduce((highest,value)=>Math.max(highest,value),-1)+1,group_id:null,group_position:null,updated_at:new Date().toISOString()}).select("id").single();if(result.error||!result.data){setMessage(result.error?.message??"Unable to save exercise.");setSaving(false);return false}const inserted=await supabase.from("gbgs_life_health_exercise_sets").insert(input.sets.map((set,index)=>({user_id:userData.user!.id,exercise_id:result.data.id,set_number:index+1,reps:Number(set.reps),weight_used:num(set.weight),weight_unit:set.unit.trim()||"lbs",notes:set.notes.trim(),updated_at:new Date().toISOString()})));if(inserted.error){await supabase.from("gbgs_life_health_exercises").delete().eq("id",result.data.id).eq("user_id",userData.user.id);setMessage(inserted.error.message);setSaving(false);return false}return finish("Exercise saved successfully.")}
  async function saveSuperset(forms:ExerciseForm[]){if(forms.length<2||forms.some(form=>!form.name.trim()||!form.sets.length||form.sets.some(set=>!Number.isInteger(Number(set.reps))||Number(set.reps)<0||(set.weight!==""&&Number(set.weight)<0)))){setMessage("A superset requires at least two named exercises with valid sets.");return false}setSaving(true);const daily=await ensureDaily();const{data:userData}=await supabase.auth.getUser();if(!daily||!userData.user){setSaving(false);return false}const orders=[...exercises.filter(item=>!item.group_id).map(item=>item.sort_order),...exerciseGroups.map(item=>item.sort_order)],sortOrder=orders.length?Math.max(...orders)+1:0;const group=await supabase.from("gbgs_life_health_exercise_groups").insert({user_id:userData.user.id,daily_health_id:daily.id,group_type:"Superset",group_name:"",sort_order:sortOrder}).select("id").single();if(group.error||!group.data){setMessage(group.error?.message??"Unable to create superset.");setSaving(false);return false}for(let position=0;position<forms.length;position++){const form=forms[position],exercise=await supabase.from("gbgs_life_health_exercises").insert({user_id:userData.user.id,daily_health_id:daily.id,exercise_name:form.name.trim(),weight_used:null,weight_unit:"lbs",notes:"",sort_order:position,group_id:group.data.id,group_position:position+1,updated_at:new Date().toISOString()}).select("id").single();if(exercise.error||!exercise.data){await supabase.from("gbgs_life_health_exercise_groups").delete().eq("id",group.data.id).eq("user_id",userData.user.id);setMessage(exercise.error?.message??"Unable to create grouped exercise.");setSaving(false);return false}const sets=await supabase.from("gbgs_life_health_exercise_sets").insert(form.sets.map((set,index)=>({user_id:userData.user!.id,exercise_id:exercise.data.id,set_number:index+1,reps:Number(set.reps),weight_used:num(set.weight),weight_unit:set.unit.trim()||"lbs",notes:set.notes.trim(),updated_at:new Date().toISOString()})));if(sets.error){await supabase.from("gbgs_life_health_exercise_groups").delete().eq("id",group.data.id).eq("user_id",userData.user.id);setMessage(sets.error.message);setSaving(false);return false}}return finish("Superset saved successfully.")}
  async function addExerciseToGroup(groupId:string,form:ExerciseForm){if(!form.name.trim()||!form.sets.length)return false;setSaving(true);const daily=await ensureDaily();const{data:userData}=await supabase.auth.getUser();if(!daily||!userData.user){setSaving(false);return false}const members=exercises.filter(item=>item.group_id===groupId),position=members.length+1,result=await supabase.from("gbgs_life_health_exercises").insert({user_id:userData.user.id,daily_health_id:daily.id,exercise_name:form.name.trim(),weight_used:null,weight_unit:"lbs",notes:"",sort_order:position-1,group_id:groupId,group_position:position,updated_at:new Date().toISOString()}).select("id").single();if(result.error||!result.data){setMessage(result.error?.message??"Unable to add grouped exercise.");setSaving(false);return false}const sets=await supabase.from("gbgs_life_health_exercise_sets").insert(form.sets.map((set,index)=>({user_id:userData.user!.id,exercise_id:result.data.id,set_number:index+1,reps:Number(set.reps),weight_used:num(set.weight),weight_unit:set.unit.trim()||"lbs",notes:set.notes.trim(),updated_at:new Date().toISOString()})));if(sets.error){await supabase.from("gbgs_life_health_exercises").delete().eq("id",result.data.id).eq("user_id",userData.user.id);setMessage(sets.error.message);setSaving(false);return false}return finish("Exercise added to superset.")}
  async function removeExerciseGroup(id:string){setSaving(true);const{data:userData}=await supabase.auth.getUser();if(!userData.user){setSaving(false);return false}const result=await supabase.from("gbgs_life_health_exercise_groups").delete().eq("id",id).eq("user_id",userData.user.id);if(result.error){setMessage(result.error.message);setSaving(false);return false}return finish("Superset deleted.")}
  async function removeGroupedExercise(item:Exercise){setSaving(true);const{data:userData}=await supabase.auth.getUser();if(!userData.user){setSaving(false);return false}const result=await supabase.from("gbgs_life_health_exercises").delete().eq("id",item.id).eq("user_id",userData.user.id);if(result.error){setMessage(result.error.message);setSaving(false);return false}const remaining=exercises.filter(exercise=>exercise.group_id===item.group_id&&exercise.id!==item.id).sort((a,b)=>(a.group_position??0)-(b.group_position??0));for(let index=0;index<remaining.length;index++)if(remaining[index].group_position!==index+1)await supabase.from("gbgs_life_health_exercises").update({group_position:index+1,sort_order:index,updated_at:new Date().toISOString()}).eq("id",remaining[index].id).eq("user_id",userData.user.id);return finish("Grouped exercise deleted.")}
  async function renameExercise(id:string,name:string){if(!name.trim())return false;setSaving(true);const{data:userData}=await supabase.auth.getUser();const result=await supabase.from("gbgs_life_health_exercises").update({exercise_name:name.trim(),updated_at:new Date().toISOString()}).eq("id",id).eq("user_id",userData.user?.id??"");if(result.error){setMessage(result.error.message);setSaving(false);return false}return finish("Exercise name updated.")}
  async function saveExerciseSet(exerciseId:string,input:ExerciseSetForm,id?:string){if(!Number.isInteger(Number(input.reps))||Number(input.reps)<0||(input.weight!==""&&Number(input.weight)<0)){setMessage("Enter valid reps and weight.");return false}setSaving(true);const{data:userData}=await supabase.auth.getUser();if(!userData.user){setSaving(false);return false}const exercise=exercises.find(item=>item.id===exerciseId);if(!exercise){setSaving(false);return false}const payload={user_id:userData.user.id,exercise_id:exerciseId,reps:Number(input.reps),weight_used:num(input.weight),weight_unit:input.unit.trim()||"lbs",notes:input.notes.trim(),updated_at:new Date().toISOString()},result=id?await supabase.from("gbgs_life_health_exercise_sets").update(payload).eq("id",id).eq("user_id",userData.user.id):await supabase.from("gbgs_life_health_exercise_sets").insert({...payload,set_number:exercise.sets.length+1});if(result.error){setMessage(result.error.message);setSaving(false);return false}return finish(id?"Set updated.":"Set added.")}
  async function removeExerciseSet(exerciseId:string,id:string){setSaving(true);const{data:userData}=await supabase.auth.getUser();if(!userData.user){setSaving(false);return false}const deleted=await supabase.from("gbgs_life_health_exercise_sets").delete().eq("id",id).eq("user_id",userData.user.id);if(deleted.error){setMessage(deleted.error.message);setSaving(false);return false}const remaining=exercises.find(item=>item.id===exerciseId)?.sets.filter(set=>set.id!==id).sort((a,b)=>a.set_number-b.set_number)??[];for(let index=0;index<remaining.length;index++){if(remaining[index].set_number!==index+1){const updated=await supabase.from("gbgs_life_health_exercise_sets").update({set_number:index+1,updated_at:new Date().toISOString()}).eq("id",remaining[index].id).eq("user_id",userData.user.id);if(updated.error){setMessage(updated.error.message);setSaving(false);return false}}}return finish("Set deleted.")}
  async function removeExercise(id:string){setSaving(true);const {data:userData}=await supabase.auth.getUser();const result=await supabase.from("gbgs_life_health_exercises").delete().eq("id",id).eq("user_id",userData.user?.id??"");if(result.error){setMessage(result.error.message);setSaving(false);return false}return finish("Exercise removed.")}
  async function saveMeal(input:MealForm,id?:string){if(!input.label.trim()||!input.name.trim()){setMessage("Add both a meal type/number and meal name.");return false}setSaving(true);const daily=await ensureNutritionDaily();const {data:userData}=await supabase.auth.getUser();if(!daily||!userData.user){setSaving(false);return false}const payload={user_id:userData.user.id,daily_health_id:daily.id,meal_label:input.label.trim(),meal_name:input.name.trim(),meal_time:input.time||null,updated_at:new Date().toISOString()};const result=id?await supabase.from("gbgs_life_health_meals").update(payload).eq("id",id).eq("user_id",userData.user.id).select("id").single():await supabase.from("gbgs_life_health_meals").insert({...payload,sort_order:meals.length}).select("id").single();if(result.error||!result.data){setMessage(result.error?.message??"Unable to save meal.");setSaving(false);return false}await finish(id?"Meal updated.":"Meal added.");return result.data.id}
  async function toggleNutritionCompleted(){setSaving(true);const daily=await ensureNutritionDaily(),{data:userData}=await supabase.auth.getUser();if(!daily||!userData.user){setSaving(false);return false}const completed=!Boolean(daily.nutrition_completed),result=await supabase.from("gbgs_life_daily_health").update({nutrition_completed:completed,updated_at:new Date().toISOString()}).eq("id",daily.id).eq("user_id",userData.user.id).eq("record_date",nutritionDate).select("*").single();if(result.error||!result.data){setMessage(result.error?.message??"Unable to update nutrition completion.");setSaving(false);return false}setNutritionRecord(result.data as DailyHealthRecord);return finish(completed?"Nutrition marked completed.":"Nutrition completion removed.")}
  async function removeMeal(id:string){setSaving(true);const {data:userData}=await supabase.auth.getUser();const result=await supabase.from("gbgs_life_health_meals").delete().eq("id",id).eq("user_id",userData.user?.id??"");if(result.error){setMessage(result.error.message);setSaving(false);return false}return finish("Meal and its foods removed.")}
  async function appendFoodItem(mealId:string,input:FoodItemAppend){setSaving(true);const targetMeal=meals.find(meal=>meal.id===mealId),{data:userData}=await supabase.auth.getUser();if(!targetMeal||!userData.user){setMessage(targetMeal?"Sign in required.":"The selected meal is not available for this nutrition date.");setSaving(false);return false}const resolved=await supabase.from("gbgs_life_health_meals").select("id,daily_health_id").eq("id",targetMeal.id).eq("daily_health_id",targetMeal.daily_health_id).eq("user_id",userData.user.id).maybeSingle();if(resolved.error||!resolved.data){setMessage(resolved.error?.message??"The selected meal is no longer available.");setSaving(false);return false}const highestSort=targetMeal.foods.reduce((highest,item)=>Math.max(highest,Number(item.sort_order)||0),-1),result=await supabase.from("gbgs_life_health_food_items").insert({user_id:userData.user.id,meal_id:resolved.data.id,...input,sort_order:highestSort+1,updated_at:new Date().toISOString()}).select("id").single();if(result.error||!result.data){setMessage(result.error?.message??"Unable to add food.");setSaving(false);return false}return finish("Food added.")}
  async function saveFood(mealId:string,input:FoodForm,id?:string){const targetMeal=meals.find(meal=>meal.id===mealId);if(!targetMeal){setMessage("The selected meal is not available for this nutrition date.");return false}const numeric=[input.servingAmount,input.grams,input.protein,input.carbs,input.fat,input.calories,input.proteinPer100g,input.carbsPer100g,input.fatPer100g,input.caloriesPer100g];if(!input.name.trim()||numeric.some(value=>value&&(!Number.isFinite(Number(value))||Number(value)<0))){setMessage("Add a food name and valid nonnegative nutrition values.");return false}const food:FoodItemAppend={recipe_id:null,custom_food_id:null,food_name:input.name.trim(),serving_amount:num(input.servingAmount),serving_unit:input.servingUnit.trim(),grams_consumed:num(input.grams),protein_g:num(input.protein)??0,carbohydrates_g:num(input.carbs)??0,fat_g:num(input.fat)??0,calories:num(input.calories)??0,nutrition_source:input.nutritionSource||"Manual",external_food_id:input.externalFoodId||null,source_food_name:input.sourceFoodName||null,protein_per_100g:num(input.proteinPer100g),carbohydrates_per_100g:num(input.carbsPer100g),fat_per_100g:num(input.fatPer100g),calories_per_100g:num(input.caloriesPer100g),manually_overridden:input.manuallyOverridden};if(!id)return appendFoodItem(mealId,food);setSaving(true);const{data:userData}=await supabase.auth.getUser();if(!userData.user){setSaving(false);return false}const result=await supabase.from("gbgs_life_health_food_items").update({...food,updated_at:new Date().toISOString()}).eq("id",id).eq("meal_id",targetMeal.id).eq("user_id",userData.user.id).is("recipe_id",null).is("custom_food_id",null).select("id").maybeSingle();if(result.error||!result.data){setMessage(result.error?.message??"Saved recipe snapshots cannot be replaced by the normal food editor.");setSaving(false);return false}return finish("Food updated.")}
  async function removeFood(id:string){setSaving(true);const {data:userData}=await supabase.auth.getUser();const result=await supabase.from("gbgs_life_health_food_items").delete().eq("id",id).eq("user_id",userData.user?.id??"");if(result.error){setMessage(result.error.message);setSaving(false);return false}return finish("Food removed.")}
  async function saveWater(input:WaterForm,id?:string){if(!Number.isFinite(Number(input.amount))||Number(input.amount)<=0){setMessage("Enter a water amount greater than zero.");return false}setSaving(true);const daily=await ensureDaily();const {data:userData}=await supabase.auth.getUser();if(!daily||!userData.user){setSaving(false);return false}const payload={user_id:userData.user.id,daily_health_id:daily.id,amount_oz:Number(input.amount),consumed_at:input.time||timeNow(),updated_at:new Date().toISOString()};const result=id?await supabase.from("gbgs_life_health_water_entries").update(payload).eq("id",id).eq("user_id",userData.user.id):await supabase.from("gbgs_life_health_water_entries").insert(payload);if(result.error){setMessage(result.error.message);setSaving(false);return false}return finish(id?"Water entry updated.":"Water added.")}
  async function removeWater(id:string){setSaving(true);const {data:userData}=await supabase.auth.getUser();const result=await supabase.from("gbgs_life_health_water_entries").delete().eq("id",id).eq("user_id",userData.user?.id??"");if(result.error){setMessage(result.error.message);setSaving(false);return false}return finish("Water entry removed.")}
  async function saveSupplement(input:SupplementForm,id?:string){if(!input.name.trim()||(input.amount&&Number(input.amount)<0)){setMessage("Add a supplement name and valid amount.");return false}setSaving(true);const daily=await ensureDaily();const {data:userData}=await supabase.auth.getUser();if(!daily||!userData.user){setSaving(false);return false}const payload={user_id:userData.user.id,daily_health_id:daily.id,supplement_name:input.name.trim(),amount:num(input.amount),unit:input.unit.trim(),taken:input.taken,taken_at:input.time||null,updated_at:new Date().toISOString()};const result=id?await supabase.from("gbgs_life_health_supplements").update(payload).eq("id",id).eq("user_id",userData.user.id):await supabase.from("gbgs_life_health_supplements").insert({...payload,sort_order:supplements.length});if(result.error){setMessage(result.error.message);setSaving(false);return false}return finish(id?"Supplement updated.":"Supplement added.")}
  async function toggleSupplement(item:Supplement){return saveSupplement({name:item.supplement_name,amount:textNum(item.amount),unit:item.unit,taken:!item.taken,time:!item.taken?(item.taken_at?.slice(0,5)??timeNow()):""},item.id)}
  async function removeSupplement(id:string){setSaving(true);const {data:userData}=await supabase.auth.getUser();const result=await supabase.from("gbgs_life_health_supplements").delete().eq("id",id).eq("user_id",userData.user?.id??"");if(result.error){setMessage(result.error.message);setSaving(false);return false}return finish("Supplement removed.")}
  const nutrition=totalsFor(meals.flatMap(item=>item.foods)),waterTotal=waterEntries.reduce((sum,item)=>sum+Number(item.amount_oz),0)
  return{todayKey,selectedDate,setSelectedDate,nutritionDate,setNutritionDate,nutritionCompleted:Boolean(nutritionRecord?.nutrition_completed),record,form,setForm,exerciseGroups,exercises,meals,waterEntries,supplements,recentFoods,week,nutrition,waterTotal,loading,saving,message,reload:load,saveDaily,completeWorkout,saveExercise,saveSuperset,addExerciseToGroup,removeExerciseGroup,removeGroupedExercise,renameExercise,saveExerciseSet,removeExerciseSet,removeExercise,saveMeal,toggleNutritionCompleted,removeMeal,appendFoodItem,saveFood,removeFood,saveWater,removeWater,saveSupplement,toggleSupplement,removeSupplement,dateShift}
}
