"use client"

import { useCallback, useEffect, useState } from "react"
import { supabase } from "@/lib/supabase"
import { localDateKey } from "@/lib/life-hq"

export type DailyFaith={id:string;user_id:string;record_date:string;scripture_reference:string;scripture_text:string;faith_focus:string;faith_notes:string;devotion_notes:string;prayer_completed:boolean;prayer_completed_at:string|null;devotion_completed:boolean;devotion_completed_at:string|null;gratitude_completed:boolean;gratitude_completed_at:string|null;reflection_grateful:string;reflection_learned:string;reflection_surrender:string}
export type FaithForm={scriptureReference:string;scriptureText:string;faithFocus:string;faithNotes:string;devotionNotes:string;reflectionGrateful:string;reflectionLearned:string;reflectionSurrender:string}
export type GratitudeItem={id:string;daily_faith_id:string;gratitude_text:string;sort_order:number}
export type PrayerItem={id:string;title:string;details:string;status:"Active"|"Answered"|"Archived";prayer_date:string;answered_date:string|null}
export type PrayerForm={title:string;details:string;status:PrayerItem["status"];prayerDate:string;answeredDate:string}
export type FaithCommitment={id:string;title:string;description:string;target_date:string|null;status:"Active"|"Completed"|"Paused";priority:"Low"|"Normal"|"High";completed_at:string|null}
export type CommitmentForm={title:string;description:string;targetDate:string;status:FaithCommitment["status"];priority:FaithCommitment["priority"]}
export type FaithWeekDay={date:string;prayer:boolean;devotion:boolean;gratitude:boolean}
const EMPTY:FaithForm={scriptureReference:"",scriptureText:"",faithFocus:"",faithNotes:"",devotionNotes:"",reflectionGrateful:"",reflectionLearned:"",reflectionSurrender:""}
const shift=(key:string,days:number)=>{const d=new Date(`${key}T12:00:00`);d.setDate(d.getDate()+days);return localDateKey(d)}
const bounds=(key:string)=>{const d=new Date(`${key}T12:00:00`),offset=(d.getDay()+6)%7;return{start:shift(key,-offset),end:shift(key,6-offset)}}
const toForm=(r:DailyFaith|null):FaithForm=>r?{scriptureReference:r.scripture_reference,scriptureText:r.scripture_text,faithFocus:r.faith_focus,faithNotes:r.faith_notes,devotionNotes:r.devotion_notes,reflectionGrateful:r.reflection_grateful,reflectionLearned:r.reflection_learned,reflectionSurrender:r.reflection_surrender}:{...EMPTY}

export function useLifeHqFaith(){
  const todayKey=localDateKey(),[selectedDate,setSelectedDate]=useState(todayKey),[record,setRecord]=useState<DailyFaith|null>(null),[form,setForm]=useState<FaithForm>({...EMPTY}),[gratitude,setGratitude]=useState<GratitudeItem[]>([]),[prayers,setPrayers]=useState<PrayerItem[]>([]),[commitments,setCommitments]=useState<FaithCommitment[]>([]),[week,setWeek]=useState<FaithWeekDay[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("")
  const load=useCallback(async()=>{setLoading(true);setMessage("");const {data:u,error:ue}=await supabase.auth.getUser();if(ue||!u.user){setMessage(ue?.message??"Sign in required.");setLoading(false);return}const b=bounds(selectedDate);const [daily,prayerRows,commitmentRows]=await Promise.all([supabase.from("gbgs_life_daily_faith").select("*").eq("user_id",u.user.id).gte("record_date",b.start).lte("record_date",b.end).order("record_date"),supabase.from("gbgs_life_faith_prayers").select("*").eq("user_id",u.user.id).order("created_at",{ascending:false}),supabase.from("gbgs_life_faith_commitments").select("*").eq("user_id",u.user.id).order("target_date",{ascending:true,nullsFirst:false})]);const error=daily.error??prayerRows.error??commitmentRows.error;if(error){setMessage(error.message);setLoading(false);return}const rows=(daily.data??[]) as DailyFaith[],selected=rows.find(r=>r.record_date===selectedDate)??null;let gratitudeRows:GratitudeItem[]=[];if(selected){const result=await supabase.from("gbgs_life_faith_gratitude_items").select("*").eq("user_id",u.user.id).eq("daily_faith_id",selected.id).order("sort_order");if(result.error){setMessage(result.error.message);setLoading(false);return}gratitudeRows=(result.data??[]) as GratitudeItem[]}const days:FaithWeekDay[]=[];for(let date=b.start;date<=b.end;date=shift(date,1)){const r=rows.find(item=>item.record_date===date);days.push({date,prayer:r?.prayer_completed??false,devotion:r?.devotion_completed??false,gratitude:r?.gratitude_completed??false})}setRecord(selected);setForm(toForm(selected));setGratitude(gratitudeRows);setPrayers((prayerRows.data??[]) as PrayerItem[]);setCommitments((commitmentRows.data??[]) as FaithCommitment[]);setWeek(days);setLoading(false)},[selectedDate])
  useEffect(()=>{void load()},[load])
  async function ensureDaily(){if(record)return record;const {data:u}=await supabase.auth.getUser();if(!u.user)return null;const {data,error}=await supabase.from("gbgs_life_daily_faith").upsert({user_id:u.user.id,record_date:selectedDate},{onConflict:"user_id,record_date"}).select("*").single();if(error){setMessage(error.message);return null}setRecord(data as DailyFaith);return data as DailyFaith}
  async function done(text:string){await load();setMessage(text);setSaving(false);return true}
  async function saveDaily(){setSaving(true);const {data:u}=await supabase.auth.getUser();if(!u.user){setSaving(false);return false}const {error}=await supabase.from("gbgs_life_daily_faith").upsert({user_id:u.user.id,record_date:selectedDate,scripture_reference:form.scriptureReference.trim(),scripture_text:form.scriptureText.trim(),faith_focus:form.faithFocus.trim(),faith_notes:form.faithNotes.trim(),devotion_notes:form.devotionNotes.trim(),reflection_grateful:form.reflectionGrateful.trim(),reflection_learned:form.reflectionLearned.trim(),reflection_surrender:form.reflectionSurrender.trim(),updated_at:new Date().toISOString()},{onConflict:"user_id,record_date"});if(error){setMessage(error.message);setSaving(false);return false}return done("Daily Faith record saved.")}
  async function toggleHabit(kind:"prayer"|"devotion"|"gratitude",completed:boolean){setSaving(true);const daily=await ensureDaily();const {data:u}=await supabase.auth.getUser();if(!daily||!u.user){setSaving(false);return false}const now=new Date().toISOString(),patch={[`${kind}_completed`]:completed,[`${kind}_completed_at`]:completed?now:null,updated_at:now};const {error}=await supabase.from("gbgs_life_daily_faith").update(patch).eq("id",daily.id).eq("user_id",u.user.id);if(error){setMessage(error.message);setSaving(false);return false}return done(`${kind[0].toUpperCase()+kind.slice(1)} updated.`)}
  async function saveGratitude(text:string,id?:string){if(!text.trim()){setMessage("Enter a gratitude item.");return false}if(!id&&gratitude.length>=3){setMessage("This daily list is limited to three items.");return false}setSaving(true);const daily=await ensureDaily();const {data:u}=await supabase.auth.getUser();if(!daily||!u.user){setSaving(false);return false}const payload={user_id:u.user.id,daily_faith_id:daily.id,gratitude_text:text.trim(),updated_at:new Date().toISOString()};const result=id?await supabase.from("gbgs_life_faith_gratitude_items").update(payload).eq("id",id).eq("user_id",u.user.id):await supabase.from("gbgs_life_faith_gratitude_items").insert({...payload,sort_order:gratitude.length});if(result.error){setMessage(result.error.message);setSaving(false);return false}await supabase.from("gbgs_life_daily_faith").update({gratitude_completed:true,gratitude_completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",daily.id).eq("user_id",u.user.id);return done(id?"Gratitude updated.":"Gratitude added.")}
  async function removeGratitude(id:string){setSaving(true);const {data:u}=await supabase.auth.getUser();if(!u.user){setSaving(false);return false}const {error}=await supabase.from("gbgs_life_faith_gratitude_items").delete().eq("id",id).eq("user_id",u.user.id);if(error){setMessage(error.message);setSaving(false);return false}if(gratitude.length===1&&record)await supabase.from("gbgs_life_daily_faith").update({gratitude_completed:false,gratitude_completed_at:null,updated_at:new Date().toISOString()}).eq("id",record.id).eq("user_id",u.user.id);return done("Gratitude removed.")}
  async function savePrayer(f:PrayerForm,id?:string){if(!f.title.trim()){setMessage("Add a prayer title or subject.");return false}setSaving(true);const {data:u}=await supabase.auth.getUser();if(!u.user){setSaving(false);return false}const payload={user_id:u.user.id,title:f.title.trim(),details:f.details.trim(),status:f.status,prayer_date:f.prayerDate||todayKey,answered_date:f.status==="Answered"?(f.answeredDate||todayKey):null,updated_at:new Date().toISOString()};const result=id?await supabase.from("gbgs_life_faith_prayers").update(payload).eq("id",id).eq("user_id",u.user.id):await supabase.from("gbgs_life_faith_prayers").insert(payload);if(result.error){setMessage(result.error.message);setSaving(false);return false}return done(id?"Prayer updated.":"Prayer added.")}
  async function removePrayer(id:string){return remove("gbgs_life_faith_prayers",id,"Prayer deleted.")}
  async function saveCommitment(f:CommitmentForm,id?:string){if(!f.title.trim()){setMessage("Add a commitment title.");return false}setSaving(true);const {data:u}=await supabase.auth.getUser();if(!u.user){setSaving(false);return false}const payload={user_id:u.user.id,title:f.title.trim(),description:f.description.trim(),target_date:f.targetDate||null,status:f.status,priority:f.priority,completed_at:f.status==="Completed"?new Date().toISOString():null,updated_at:new Date().toISOString()};const result=id?await supabase.from("gbgs_life_faith_commitments").update(payload).eq("id",id).eq("user_id",u.user.id):await supabase.from("gbgs_life_faith_commitments").insert(payload);if(result.error){setMessage(result.error.message);setSaving(false);return false}return done(id?"Commitment updated.":"Commitment added.")}
  async function removeCommitment(id:string){return remove("gbgs_life_faith_commitments",id,"Commitment deleted.")}
  async function remove(table:string,id:string,text:string){setSaving(true);const {data:u}=await supabase.auth.getUser();if(!u.user){setSaving(false);return false}const {error}=await supabase.from(table).delete().eq("id",id).eq("user_id",u.user.id);if(error){setMessage(error.message);setSaving(false);return false}return done(text)}
  return{todayKey,selectedDate,setSelectedDate,dateShift:shift,record,form,setForm,gratitude,prayers,commitments,week,loading,saving,message,setMessage,saveDaily,toggleHabit,saveGratitude,removeGratitude,savePrayer,removePrayer,saveCommitment,removeCommitment}
}
