"use client"
import {useCallback,useEffect,useState} from "react"
import {supabase} from "@/lib/supabase"
import {localDateKey,packLifeNotes} from "@/lib/life-hq"
export type Goal={id:string;user_id:string;goal_name:string;category:string;description:string;why_it_matters:string;start_date:string;target_date:string|null;progress_percent:number;status:"Active"|"Completed"|"Paused"|"Cancelled";notes:string;completed_at:string|null;created_at:string;updated_at:string}
export type GoalForm={name:string;category:string;description:string;why:string;startDate:string;targetDate:string;progress:string;status:Goal["status"];notes:string}
export type GoalAction={id:string;user_id:string;goal_id:string;action_title:string;action_date:string;scheduled_time:string|null;priority:"High"|"Medium"|"Low";status:"Planned"|"Completed"|"Skipped";notes:string;estimated_minutes:number|null;actual_minutes:number|null;calendar_event_id:string|null;completed_at:string|null}
export type ActionForm={goalId:string;title:string;date:string;time:string;priority:GoalAction["priority"];status:GoalAction["status"];notes:string;estimated:string;actual:string}
export type Milestone={id:string;goal_id:string;milestone_title:string;target_date:string|null;status:"Not Started"|"In Progress"|"Completed";completion_date:string|null;sort_order:number;notes:string}
export type MilestoneForm={goalId:string;title:string;targetDate:string;status:Milestone["status"];notes:string}
export type Progress={id:string;goal_id:string;progress_percent:number;recorded_date:string;notes:string;created_at:string}
export type GoalNote={id:string;goal_id:string;note_type:"Note"|"Obstacle"|"Win"|"Next Step";content:string;created_at:string}
export type NoteForm={goalId:string;type:GoalNote["note_type"];content:string}
const shift=(key:string,n:number)=>{const d=new Date(`${key}T12:00:00`);d.setDate(d.getDate()+n);return localDateKey(d)},week=(key:string)=>{const d=new Date(`${key}T12:00:00`),o=(d.getDay()+6)%7;return{start:shift(key,-o),end:shift(key,6-o)}}
const num=(v:string)=>v===""?null:Number(v)
export function useLifeHqGoals(){const todayKey=localDateKey(),[selectedDate,setSelectedDate]=useState(todayKey),[goals,setGoals]=useState<Goal[]>([]),[actions,setActions]=useState<GoalAction[]>([]),[weekActions,setWeekActions]=useState<GoalAction[]>([]),[milestones,setMilestones]=useState<Milestone[]>([]),[progress,setProgress]=useState<Progress[]>([]),[notes,setNotes]=useState<GoalNote[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState("");const load=useCallback(async()=>{setLoading(true);setMessage("");const{data:u,error:ue}=await supabase.auth.getUser();if(ue||!u.user){setMessage(ue?.message??"Sign in required.");setLoading(false);return}const b=week(selectedDate),[g,a,w,m,p,n]=await Promise.all([supabase.from("gbgs_life_goals").select("*").eq("user_id",u.user.id).order("target_date",{ascending:true,nullsFirst:false}),supabase.from("gbgs_life_goal_actions").select("*").eq("user_id",u.user.id).eq("action_date",selectedDate).order("scheduled_time",{ascending:true,nullsFirst:false}),supabase.from("gbgs_life_goal_actions").select("*").eq("user_id",u.user.id).gte("action_date",b.start).lte("action_date",b.end),supabase.from("gbgs_life_goal_milestones").select("*").eq("user_id",u.user.id).order("sort_order"),supabase.from("gbgs_life_goal_progress_history").select("*").eq("user_id",u.user.id).order("recorded_date"),supabase.from("gbgs_life_goal_notes").select("*").eq("user_id",u.user.id).order("created_at",{ascending:false})]);const e=g.error??a.error??w.error??m.error??p.error??n.error;if(e)setMessage(e.message);else{setGoals((g.data??[]) as Goal[]);setActions((a.data??[]) as GoalAction[]);setWeekActions((w.data??[]) as GoalAction[]);setMilestones((m.data??[]) as Milestone[]);setProgress((p.data??[]) as Progress[]);setNotes((n.data??[]) as GoalNote[])}setLoading(false)},[selectedDate]);useEffect(()=>{void load()},[load]);async function finish(t:string){await load();setMessage(t);setSaving(false);return true}async function user(){const{data}=await supabase.auth.getUser();return data.user}
async function saveGoal(f:GoalForm,id?:string){if(!f.name.trim()||!Number.isFinite(Number(f.progress))||Number(f.progress)<0||Number(f.progress)>100){setMessage("Add a goal name and progress from 0 to 100.");return false}setSaving(true);const u=await user();if(!u){setSaving(false);return false}const old=goals.find(g=>g.id===id),now=new Date().toISOString(),payload={user_id:u.id,goal_name:f.name.trim(),category:f.category.trim()||"Personal",description:f.description.trim(),why_it_matters:f.why.trim(),start_date:f.startDate||todayKey,target_date:f.targetDate||null,progress_percent:Number(f.progress),status:f.status,notes:f.notes.trim(),completed_at:f.status==="Completed"?(old?.completed_at??now):null,updated_at:now};const result=id?await supabase.from("gbgs_life_goals").update(payload).eq("id",id).eq("user_id",u.id).select("id").single():await supabase.from("gbgs_life_goals").insert(payload).select("id").single();if(result.error||!result.data){setMessage(result.error?.message??"Unable to save goal.");setSaving(false);return false}if(!old||old.progress_percent!==Number(f.progress)){const h=await supabase.from("gbgs_life_goal_progress_history").upsert({user_id:u.id,goal_id:result.data.id,progress_percent:Number(f.progress),recorded_date:todayKey,notes:""},{onConflict:"goal_id,recorded_date,progress_percent"});if(h.error){setMessage(h.error.message);setSaving(false);return false}}return finish(id?"Goal updated.":"Goal added.")}
async function saveAction(f:ActionForm,id?:string){if(!f.goalId||!f.title.trim()){setMessage("Choose a goal and add an action title.");return false}if([f.estimated,f.actual].some(v=>v!==""&&Number(v)<0)){setMessage("Minutes cannot be negative.");return false}setSaving(true);const u=await user();if(!u){setSaving(false);return false}const old=actions.find(a=>a.id===id)??weekActions.find(a=>a.id===id),now=new Date().toISOString(),payload={user_id:u.id,goal_id:f.goalId,action_title:f.title.trim(),action_date:f.date,scheduled_time:f.time||null,priority:f.priority,status:f.status,notes:f.notes.trim(),estimated_minutes:num(f.estimated),actual_minutes:num(f.actual),completed_at:f.status==="Completed"?(old?.completed_at??now):null,updated_at:now};const r=id?await supabase.from("gbgs_life_goal_actions").update(payload).eq("id",id).eq("user_id",u.id).select("*").single():await supabase.from("gbgs_life_goal_actions").insert(payload).select("*").single();if(r.error||!r.data){setMessage(r.error?.message??"Unable to save action.");setSaving(false);return false}let saved=r.data as GoalAction;const should=Boolean(saved.scheduled_time);if(!should&&saved.calendar_event_id){await supabase.from("gbgs_calendar_events").delete().eq("id",saved.calendar_event_id).eq("user_id",u.id).eq("source","Life Goals");await supabase.from("gbgs_life_goal_actions").update({calendar_event_id:null}).eq("id",saved.id).eq("user_id",u.id)}else if(should){const cal={title:`Goal: ${saved.action_title}`,event_date:saved.action_date,start_time:saved.scheduled_time,end_time:null,category:"Goals",notes:packLifeNotes(saved.notes,"Personal"),completed:saved.status==="Completed",source:"Life Goals",source_id:saved.id,updated_at:now};let cid=saved.calendar_event_id;if(!cid){const x=await supabase.from("gbgs_calendar_events").select("id").eq("user_id",u.id).eq("source","Life Goals").eq("source_id",saved.id).maybeSingle();cid=x.data?.id??null}const c=cid?await supabase.from("gbgs_calendar_events").update(cal).eq("id",cid).eq("user_id",u.id).select("id").single():await supabase.from("gbgs_calendar_events").insert({...cal,user_id:u.id}).select("id").single();if(c.error||!c.data){setMessage(`Action saved, but calendar sync failed: ${c.error?.message??"Unknown error"}`);setSaving(false);return false}if(saved.calendar_event_id!==c.data.id)await supabase.from("gbgs_life_goal_actions").update({calendar_event_id:c.data.id}).eq("id",saved.id).eq("user_id",u.id)}return finish(id?"Action updated.":"Action added.")}
async function saveMilestone(f:MilestoneForm,id?:string){if(!f.goalId||!f.title.trim()){setMessage("Choose a goal and add a milestone title.");return false}setSaving(true);const u=await user();if(!u){setSaving(false);return false}const payload={user_id:u.id,goal_id:f.goalId,milestone_title:f.title.trim(),target_date:f.targetDate||null,status:f.status,completion_date:f.status==="Completed"?todayKey:null,notes:f.notes.trim(),updated_at:new Date().toISOString()};const r=id?await supabase.from("gbgs_life_goal_milestones").update(payload).eq("id",id).eq("user_id",u.id):await supabase.from("gbgs_life_goal_milestones").insert({...payload,sort_order:milestones.filter(m=>m.goal_id===f.goalId).length});if(r.error){setMessage(r.error.message);setSaving(false);return false}return finish(id?"Milestone updated.":"Milestone added.")}
async function saveNote(f:NoteForm,id?:string){if(!f.goalId||!f.content.trim()){setMessage("Choose a goal and enter note content.");return false}setSaving(true);const u=await user();if(!u){setSaving(false);return false}const payload={user_id:u.id,goal_id:f.goalId,note_type:f.type,content:f.content.trim(),updated_at:new Date().toISOString()};const r=id?await supabase.from("gbgs_life_goal_notes").update(payload).eq("id",id).eq("user_id",u.id):await supabase.from("gbgs_life_goal_notes").insert(payload);if(r.error){setMessage(r.error.message);setSaving(false);return false}return finish(id?"Goal note updated.":"Goal note added.")}
async function remove(table:string,id:string,text:string){setSaving(true);const u=await user();if(!u){setSaving(false);return false}if(table==="gbgs_life_goal_actions"){const a=actions.find(x=>x.id===id);if(a?.calendar_event_id)await supabase.from("gbgs_calendar_events").delete().eq("id",a.calendar_event_id).eq("user_id",u.id).eq("source","Life Goals")}const r=await supabase.from(table).delete().eq("id",id).eq("user_id",u.id);if(r.error){setMessage(r.error.message);setSaving(false);return false}return finish(text)}
return{todayKey,selectedDate,setSelectedDate,dateShift:shift,goals,actions,weekActions,milestones,progress,notes,loading,saving,message,setMessage,saveGoal,saveAction,saveMilestone,saveNote,removeGoal:(id:string)=>remove("gbgs_life_goals",id,"Goal deleted."),removeAction:(id:string)=>remove("gbgs_life_goal_actions",id,"Action deleted."),removeMilestone:(id:string)=>remove("gbgs_life_goal_milestones",id,"Milestone deleted."),removeNote:(id:string)=>remove("gbgs_life_goal_notes",id,"Note deleted.")}}
